/*
 * Copyright (C) 2017-2018 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package com.here.ort.model.config

/**
 * A mapping from license strings collected from the declared licenses of open source packages to SPDX license
 * identifiers.
 */
object LicenseMapping {
    private val mapping = mapOf(
        "(0BSD OR MIT)" to setOf(SpdxLicense._0BSD, SpdxLicense.MIT),
        "(BSD-2-Clause OR MIT OR Apache-2.0)" to setOf(
            SpdxLicense.BSD_2_CLAUSE,
            SpdxLicense.MIT,
            SpdxLicense.APACHE_2_0
        ),
        "(BSD-2-Clause OR MIT)" to setOf(SpdxLicense.BSD_2_CLAUSE, SpdxLicense.MIT),
        "(BSD-2-Clause OR WTFPL)" to setOf(SpdxLicense.BSD_2_CLAUSE, SpdxLicense.WTFPL),
        "(BSD-3-Clause OR GPL-2.0)" to setOf(SpdxLicense.BSD_3_CLAUSE, SpdxLicense.GPL_2_0),
        "(EDL-1.0 OR EPL-1.0)" to setOf(SpdxLicense.EPL_1_0),
        "(GPL-2.0 OR MIT)" to setOf(SpdxLicense.GPL_2_0, SpdxLicense.MIT),
        "(MIT AND BSD-3-Clause)" to setOf(SpdxLicense.MIT, SpdxLicense.BSD_3_CLAUSE),
        "(MIT AND CC-BY-3.0)" to setOf(SpdxLicense.MIT, SpdxLicense.CC_BY_3_0),
        "(MIT AND JSON)" to setOf(SpdxLicense.MIT, SpdxLicense.JSON),
        "(MIT AND Zlib)" to setOf(SpdxLicense.MIT, SpdxLicense.ZLIB),
        "(MIT OR Apache-2.0)" to setOf(SpdxLicense.MIT, SpdxLicense.APACHE_2_0),
        "(MIT OR GPL-2.0)" to setOf(SpdxLicense.MIT, SpdxLicense.GPL_2_0),
        "(MIT OR GPL-3.0)" to setOf(SpdxLicense.MIT, SpdxLicense.GPL_3_0),
        "(MIT)" to setOf(SpdxLicense.MIT),
        "(MIT-style) netCDF C library license" to setOf(SpdxLicense.NETCDF),
        "(OFL-1.1 AND MIT)" to setOf(SpdxLicense.OFL_1_1, SpdxLicense.MIT),
        "(OFL-1.1 OR MIT)" to setOf(SpdxLicense.OFL_1_1, SpdxLicense.MIT),
        "(WTFPL OR MIT)" to setOf(SpdxLicense.WTFPL, SpdxLicense.MIT),
        "2-clause BSD license" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "2-clause BSDL" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "3-Clause BSD" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "3-Clause BSD License" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "3-clause BSD" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "AFLv2.1" to setOf(SpdxLicense.AFL_2_1),
        "AL 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "ALv2" to setOf(SpdxLicense.APACHE_2_0),
        "APL2" to setOf(SpdxLicense.APACHE_2_0),
        "APLv2.0" to setOf(SpdxLicense.APACHE_2_0),
        "ASF 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "ASL" to setOf(SpdxLicense.APACHE_2_0),
        "ASL 2" to setOf(SpdxLicense.APACHE_2_0),
        "ASL 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "ASL, version 2" to setOf(SpdxLicense.APACHE_2_0),
        "Academic Free License (AFL)" to setOf(SpdxLicense.AFL_2_1),
        "Apache" to setOf(SpdxLicense.APACHE_2_0),
        "Apache  Version 2.0, January 2004" to setOf(SpdxLicense.APACHE_2_0),
        "Apache 2" to setOf(SpdxLicense.APACHE_2_0),
        "Apache 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache 2.0 License" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License (2.0)" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License 2" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License V2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License Version 2" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License Version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License v2" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License v2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License, 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License, V2.0 or later" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License, Version 2" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License, Version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        """Apache License, Version 2.0 and
        Common Development And Distribution License (CDDL) Version 1.0 """.trimIndent()
                to setOf(SpdxLicense.APACHE_2_0, SpdxLicense.CDDL_1_0),
        "Apache License, version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache License,Version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache Public License 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache Software" to setOf(SpdxLicense.APACHE_2_0),
        "Apache Software License - Version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache Software License 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache Software License, Version 1.1" to setOf(SpdxLicense.APACHE_1_1),
        "Apache Software License, version 1.1" to setOf(SpdxLicense.APACHE_1_1),
        "Apache Software License, version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache Software Licenses" to setOf(SpdxLicense.APACHE_2_0),
        "Apache license" to setOf(SpdxLicense.APACHE_2_0),
        "Apache v2" to setOf(SpdxLicense.APACHE_2_0),
        "Apache v2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache, Version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "Apache-2" to setOf(SpdxLicense.APACHE_2_0),
        "Apache-2.0" to setOf(SpdxLicense.APACHE_2_0),
        """Apache-2.0 */ &#39; &quot; &#x3D;end --

 """.trimIndent() to setOf(SpdxLicense.APACHE_2_0),
        "Apache2" to setOf(SpdxLicense.APACHE_2_0),
        "Artistic 2.0" to setOf(SpdxLicense.ARTISTIC_2_0),
        "Artistic-2.0" to setOf(SpdxLicense.ARTISTIC_2_0),
        "BOOST" to setOf(SpdxLicense.BSL_1_0),
        "BSD" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "BSD (3-clause)" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD - See ndg/httpsclient/LICENCE file for details" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD 2-Clause" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "BSD 2-Clause License" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "BSD 3 Clause" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD 3-Clause" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD 3-Clause \"New\" or \"Revised\" License (BSD-3-Clause)" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD 3-Clause License" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD 3-Clause license" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD 3-clause" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD Licence 3" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD License" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "BSD License for HSQL" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD New" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD New license" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD licence" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "BSD license" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "BSD or Apache License, Version 2.0" to setOf(SpdxLicense.BSD_2_CLAUSE, SpdxLicense.APACHE_2_0),
        "BSD style" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD style license" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD*" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD-2-Clause" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "BSD-3" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD-3-Clause" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD-3-Clause OR MIT" to setOf(SpdxLicense.BSD_3_CLAUSE, SpdxLicense.MIT),
        "BSD-4-Clause" to setOf(SpdxLicense.BSD_4_CLAUSE),
        "BSD-Style" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD-Style License" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD-like" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD-style" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD-style license" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "BSD2" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "BSD3" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "Beerware" to setOf(SpdxLicense.BEERWARE),
        "Berkeley Software Distribution (BSD) License" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "Bouncy Castle Licence" to setOf(SpdxLicense.MIT),
        "Bouncy Castle License" to setOf(SpdxLicense.MIT),
        "CC-BY-3.0" to setOf(SpdxLicense.CC_BY_3_0),
        "CC-BY-4.0" to setOf(SpdxLicense.CC_BY_4_0),
        "CC-BY-SA-2.0" to setOf(SpdxLicense.CC_BY_SA_2_0),
        "CC0" to setOf(SpdxLicense.CC0_1_0),
        "CC0 1.0 Universal" to setOf(SpdxLicense.CC0_1_0),
        "CC0 1.0 Universal License" to setOf(SpdxLicense.CC0_1_0),
        "CC0-1.0" to setOf(SpdxLicense.CC0_1_0),
        "CDDL" to setOf(SpdxLicense.CDDL_1_0),
        "CDDL + GPLv2 with classpath exception" to setOf(
            SpdxLicense.CDDL_1_0,
            SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION
        ),
        "CDDL 1.0" to setOf(SpdxLicense.CDDL_1_0),
        "CDDL 1.1" to setOf(SpdxLicense.CDDL_1_1),
        "CDDL License" to setOf(SpdxLicense.CDDL_1_0),
        "CDDL or GPL 2 with Classpath Exception" to setOf(
            SpdxLicense.CDDL_1_0,
            SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION
        ),
        "CDDL or GPLv2 with exceptions" to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION),
        "CDDL v1.0 / GPL v2 dual license" to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0),
        "CDDL v1.1 / GPL v2 dual license" to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0),
        "CDDL+GPL" to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0),
        "CDDL+GPL License" to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0),
        "CDDL+GPLv2" to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0),
        "CDDL/GPLv2 dual license" to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0),
        "CDDL/GPLv2+CE" to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION),
        "COMMON DEVELOPMENT AND DISTRIBUTION LICENSE" to setOf(SpdxLicense.CDDL_1_0),
        "COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0" to setOf(SpdxLicense.CDDL_1_0),
        "CPL" to setOf(SpdxLicense.CPL_1_0),
        "Cecill-C" to setOf(SpdxLicense.CECILL_C),
        "Common Development and Distribution License" to setOf(SpdxLicense.CDDL_1_0),
        "Common Development and Distribution License (CDDL) v1.0" to setOf(SpdxLicense.CDDL_1_0),
        "Common Development and Distribution License (CDDL), Version 1.1" to setOf(SpdxLicense.CDDL_1_1),
        "Common Public License - v 1.0" to setOf(SpdxLicense.CPL_1_0),
        "Common Public License Version 1.0" to setOf(SpdxLicense.CPL_1_0),
        "Creative Commons 3.0 BY-SA" to setOf(SpdxLicense.CC_BY_SA_3_0),
        "Dual License: CDDL 1.0 and GPL V2 with Classpath Exception"
                to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0),
        "Dual license consisting of the CDDL v1.1 and GPL v2" to setOf(SpdxLicense.CDDL_1_1, SpdxLicense.GPL_2_0),
        "EPL" to setOf(SpdxLicense.EPL_1_0),
        "EPL (Eclipse Public License), V1.0 or later" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Distribution License (EDL), Version 1.0" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "Eclipse Distribution License (New BSD License)" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "Eclipse Distribution License - v 1.0" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "Eclipse Distribution License v. 1.0" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "Eclipse Public License" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Public License (EPL)" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Public License (EPL) 1.0" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Public License (EPL), Version 1.0" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Public License - Version 1.0" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Public License - v 1.0" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Public License 1.0" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Public License v1.0" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Public License v2.0" to setOf(SpdxLicense.EPL_2_0),
        "Eclipse Public License, Version 1.0" to setOf(SpdxLicense.EPL_1_0),
        "Eclipse Publish License, Version 1.0" to setOf(SpdxLicense.EPL_1_0),
        "FreeBSD" to setOf(SpdxLicense.BSD_2_CLAUSE_FREEBSD),
        "GNU Affero General Public License v3" to setOf(SpdxLicense.AGPL_3_0),
        "GNU GENERAL PUBLIC LICENSE Version 2, June 1991" to setOf(SpdxLicense.GPL_2_0),
        "GNU GPL v2" to setOf(SpdxLicense.GPL_2_0),
        "GNU General Lesser Public License (LGPL) version 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "GNU General Public Library" to setOf(SpdxLicense.GPL_3_0),
        "GNU General Public License (GPL)" to setOf(SpdxLicense.GPL_3_0),
        "GNU General Public License (GPL), version 2, with the Classpath exception" to setOf(SpdxLicense.GPL_2_0),
        "GNU General Public License Version 2" to setOf(SpdxLicense.GPL_2_0),
        "GNU General Public License v2 or later (GPLv2+)" to setOf(SpdxLicense.GPL_2_0PLUS),
        "GNU General Public License v3 (GPLv3)" to setOf(SpdxLicense.GPL_3_0),
        "GNU General Public License v3 or later (GPLv3+)" to setOf(SpdxLicense.GPL_3_0PLUS),
        "GNU General Public License, Version 2 with the Classpath Exception"
                to setOf(SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION),
        "GNU General Public License, Version 3" to setOf(SpdxLicense.GPL_3_0),
        "GNU General Public License, version 2 (GPL2), with the classpath exception"
                to setOf(SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION),
        "GNU General Public License, version 2, with the Classpath Exception"
                to setOf(SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION),
        "GNU LESSER GENERAL PUBLIC LICENSE" to setOf(SpdxLicense.LGPL_2_1),
        "GNU LESSER GENERAL PUBLIC LICENSE V3.0" to setOf(SpdxLicense.LGPL_3_0),
        "GNU LESSER GENERAL PUBLIC LICENSE Version 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "GNU LGP (GNU General Public License), V2 or later" to setOf(SpdxLicense.LGPL_2_0PLUS),
        "GNU LGPL" to setOf(SpdxLicense.LGPL_2_1),
        "GNU LGPL (GNU Lesser General Public License), V2.1 or later" to setOf(SpdxLicense.LGPL_2_1PLUS),
        "GNU Lesser General Public Licence" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Lesser General Public License" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Lesser General Public License (LGPL)" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Lesser General Public License (LGPL), Version 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Lesser General Public License (LGPL), Version 3" to setOf(SpdxLicense.LGPL_3_0),
        "GNU Lesser General Public License 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Lesser General Public License Version 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Lesser General Public License Version 2.1, February 1999" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Lesser General Public License v2 or later (LGPLv2+)" to setOf(SpdxLicense.LGPL_2_0PLUS),
        "GNU Lesser General Public License v3 (LGPLv3)" to setOf(SpdxLicense.LGPL_3_0),
        "GNU Lesser General Public License v3 or later (LGPLv3+)" to setOf(SpdxLicense.LGPL_3_0PLUS),
        "GNU Lesser General Public License v3+" to setOf(SpdxLicense.LGPL_3_0PLUS),
        "GNU Lesser General Public License, Version 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Lesser General Public License, version 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Lesser Public License" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Library or Lesser General Public License (LGPL)" to setOf(SpdxLicense.LGPL_2_1),
        "GNU Public" to setOf(SpdxLicense.GPL_2_0),
        "GPL" to setOf(SpdxLicense.GPL_2_0),
        "GPL (with dual licensing option)" to setOf(SpdxLicense.GPL_2_0),
        "GPL 3" to setOf(SpdxLicense.GPL_3_0),
        "GPL v2 with ClassPath Exception" to setOf(SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION),
        "GPL version 2" to setOf(SpdxLicense.GPL_2_0),
        "GPL-2" to setOf(SpdxLicense.GPL_2_0),
        "GPL-2.0" to setOf(SpdxLicense.GPL_2_0),
        "GPL-2.0+" to setOf(SpdxLicense.GPL_2_0PLUS),
        "GPL-3.0" to setOf(SpdxLicense.GPL_3_0),
        "GPL2" to setOf(SpdxLicense.GPL_2_0),
        "GPL2 w/ CPE" to setOf(SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION),
        "GPLv2" to setOf(SpdxLicense.GPL_2_0),
        "GPLv2+CE" to setOf(SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION),
        "GPLv3" to setOf(SpdxLicense.GPL_3_0),
        "HSQLDB License" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "HSQLDB License, a BSD open source license" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "ICU License" to setOf(SpdxLicense.ICU),
        "ISC" to setOf(SpdxLicense.ISC),
        "ISC License (ISCL)" to setOf(SpdxLicense.ISC),
        "ISC license" to setOf(SpdxLicense.ISC),
        "ISC/BSD License" to setOf(SpdxLicense.ISC, SpdxLicense.BSD_2_CLAUSE),
        "Jython Software License" to setOf(SpdxLicense.PYTHON_2_0),
        "Kirkk.com BSD License" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "LGPL" to setOf(SpdxLicense.LGPL_2_1),
        "LGPL 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "LGPL 3" to setOf(SpdxLicense.LGPL_3_0),
        "LGPL 3.0" to setOf(SpdxLicense.LGPL_3_0),
        "LGPL v3" to setOf(SpdxLicense.LGPL_3_0),
        "LGPL with exceptions or ZPL" to setOf(SpdxLicense.LGPL_3_0, SpdxLicense.ZPL_2_1),
        "LGPL+BSD" to setOf(SpdxLicense.LGPL_2_1, SpdxLicense.BSD_2_CLAUSE),
        "LGPL, version 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "LGPL-2.1+" to setOf(SpdxLicense.LGPL_2_1PLUS),
        "LGPL-3" to setOf(SpdxLicense.LGPL_3_0),
        "LGPL/MIT" to setOf(SpdxLicense.LGPL_3_0, SpdxLicense.MIT),
        "LGPL3" to setOf(SpdxLicense.LGPL_3_0),
        "LGPLv3" to setOf(SpdxLicense.LGPL_3_0),
        "LGPLv3 or later" to setOf(SpdxLicense.LGPL_3_0PLUS),
        "LGPLv3+" to setOf(SpdxLicense.LGPL_3_0PLUS),
        "Lesser General Public License (LGPL)" to setOf(SpdxLicense.LGPL_2_1),
        "Lesser General Public License, version 3 or greater" to setOf(SpdxLicense.LGPL_3_0PLUS),
        "License :: OSI Approved :: Apache Software" to setOf(SpdxLicense.APACHE_2_0),
        "License :: OSI Approved :: MIT" to setOf(SpdxLicense.MIT),
        "License :: OSI Approved :: MIT License (http://opensource.org/licenses/MIT)" to setOf(SpdxLicense.MIT),
        "License Agreement For Open Source Computer Vision Library (3-clause BSD License)"
                to setOf(SpdxLicense.BSD_3_CLAUSE),
        "MIT" to setOf(SpdxLicense.MIT),
        "MIT / http://rem.mit-license.org" to setOf(SpdxLicense.MIT),
        "MIT Licence" to setOf(SpdxLicense.MIT),
        "MIT License" to setOf(SpdxLicense.MIT),
        "MIT licence" to setOf(SpdxLicense.MIT),
        "MIT license" to setOf(SpdxLicense.MIT),
        "MIT or GPL-2.0" to setOf(SpdxLicense.MIT, SpdxLicense.GPL_2_0),
        "MIT or GPLv3" to setOf(SpdxLicense.MIT, SpdxLicense.GPL_3_0),
        "MIT, 2-clause BSD" to setOf(SpdxLicense.MIT, SpdxLicense.BSD_2_CLAUSE),
        "MIT-like" to setOf(SpdxLicense.MIT),
        "MIT-style" to setOf(SpdxLicense.MIT),
        "MIT/Expat" to setOf(SpdxLicense.MIT),
        "MIT/X11" to setOf(SpdxLicense.MIT, SpdxLicense.X11),
        "MPL" to setOf(SpdxLicense.MPL_2_0),
        "MPL 1.1" to setOf(SpdxLicense.MPL_1_1),
        "MPL 2.0" to setOf(SpdxLicense.MPL_2_0),
        "MPL 2.0 or EPL 1.0" to setOf(SpdxLicense.MPL_2_0, SpdxLicense.EPL_1_0),
        "MPL 2.0, and EPL 1.0" to setOf(SpdxLicense.MPL_2_0, SpdxLicense.EPL_1_0),
        "MPL v2" to setOf(SpdxLicense.MPL_2_0),
        "MPL-2.0" to setOf(SpdxLicense.MPL_2_0),
        "MPL-2.0 OR Apache-2.0" to setOf(SpdxLicense.MPL_2_0, SpdxLicense.APACHE_2_0),
        "MPLv2.0" to setOf(SpdxLicense.MPL_2_0),
        "Mockrunner License, based on Apache Software License, version 1.1" to setOf(SpdxLicense.APACHE_1_1),
        "Mozilla Public License" to setOf(SpdxLicense.MPL_2_0),
        "Mozilla Public License 1.1 (MPL 1.1)" to setOf(SpdxLicense.MPL_1_1),
        "Mozilla Public License 2.0 (MPL 2.0)" to setOf(SpdxLicense.MPL_2_0),
        "Mozilla Public License Version 1.0" to setOf(SpdxLicense.MPL_1_0),
        "Mozilla Public License Version 1.1" to setOf(SpdxLicense.MPL_1_1),
        "Mozilla Public License Version 2.0" to setOf(SpdxLicense.MPL_2_0),
        "Mozilla Public License version 1.1" to setOf(SpdxLicense.MPL_1_1),
        "Mozilla Public License version 2.0" to setOf(SpdxLicense.MPL_2_0),
        "Mozilla Public License, Version 2.0" to setOf(SpdxLicense.MPL_2_0),
        "Mozilla Public License, version 2.0" to setOf(SpdxLicense.MPL_2_0),
        "NetBeans CDDL/GPL" to setOf(SpdxLicense.CDDL_1_0, SpdxLicense.GPL_2_0),
        "New BSD" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "New BSD License" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "New BSD license" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "Perl Artistic v2" to setOf(SpdxLicense.ARTISTIC_1_0_PERL),
        "Public Domain, per Creative Commons CC0" to setOf(SpdxLicense.CC0_1_0),
        "Public domain (CC0-1.0)" to setOf(SpdxLicense.CC0_1_0),
        "Python Software Foundation" to setOf(SpdxLicense.PYTHON_2_0),
        "Ruby" to setOf(SpdxLicense.RUBY),
        "Ruby or LGPLv3+" to setOf(SpdxLicense.RUBY, SpdxLicense.LGPL_3_0PLUS),
        "Ruby's" to setOf(SpdxLicense.RUBY),
        "Sleepycat License" to setOf(SpdxLicense.SLEEPYCAT),
        "TMate Open Source License (with dual licensing option)" to setOf(SpdxLicense.TMATE),
        "The (New) BSD License" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "The Apache License" to setOf(SpdxLicense.APACHE_2_0),
        "The Apache License, Version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "The Apache Software Licence, Version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "The Apache Software License, Version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "The Apache Software License, version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "The BSD 2-Clause License" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "The BSD 3-Clause License" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "The BSD License" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "The BSD Software License" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "The Eclipse Public License Version 1.0" to setOf(SpdxLicense.EPL_1_0),
        "The GNU General Public License (GPL), Version 2, With Classpath Exception"
                to setOf(SpdxLicense.GPL_2_0_WITH_CLASSPATH_EXCEPTION),
        "The GNU General Public License, Version 2" to setOf(SpdxLicense.GPL_2_0),
        "The GNU Lesser General Public License, Version 2.1" to setOf(SpdxLicense.LGPL_2_1),
        "The JSON License" to setOf(SpdxLicense.JSON),
        "The MIT" to setOf(SpdxLicense.MIT),
        "The MIT License" to setOf(SpdxLicense.MIT),
        "The MIT License (MIT)" to setOf(SpdxLicense.MIT),
        "The MIT License(MIT)" to setOf(SpdxLicense.MIT),
        "The MIT license" to setOf(SpdxLicense.MIT),
        "The New BSD License" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "The PostgreSQL License" to setOf(SpdxLicense.POSTGRESQL),
        "The SAX License" to setOf(SpdxLicense.SAX_PD),
        "The Unlicense" to setOf(SpdxLicense.UNLICENSE),
        "The W3C License" to setOf(SpdxLicense.W3C),
        "The W3C Software License" to setOf(SpdxLicense.W3C),
        "Three-clause BSD-style" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "Two-clause BSD-style license" to setOf(SpdxLicense.BSD_2_CLAUSE),
        "UNLICENSE" to setOf(SpdxLicense.UNLICENSE),
        "UNLICENSED" to setOf(SpdxLicense.UNLICENSE),
        "Unicode/ICU License" to setOf(SpdxLicense.ICU),
        "Unlicense" to setOf(SpdxLicense.UNLICENSE),
        "WTFPL" to setOf(SpdxLicense.WTFPL),
        "WTFPL OR ISC" to setOf(SpdxLicense.WTFPL, SpdxLicense.ISC),
        "WTFPL OR MIT" to setOf(SpdxLicense.WTFPL, SpdxLicense.MIT),
        "ZPL 2.1" to setOf(SpdxLicense.ZPL_2_1),
        "Zlib" to setOf(SpdxLicense.ZLIB),
        "Zope Public" to setOf(SpdxLicense.ZPL_2_1),
        "apache-2.0" to setOf(SpdxLicense.APACHE_2_0),
        "boost" to setOf(SpdxLicense.BSL_1_0),
        "http://ant-contrib.sourceforge.net/tasks/LICENSE.txt" to setOf(SpdxLicense.APACHE_1_1),
        "http://opensource.org/licenses/MIT" to setOf(SpdxLicense.MIT),
        "http://svnkit.com/license.html" to setOf(SpdxLicense.TMATE),
        "http://www.apache.org/licenses/LICENSE-2.0" to setOf(SpdxLicense.APACHE_2_0),
        "http://www.apache.org/licenses/LICENSE-2.0.txt" to setOf(SpdxLicense.APACHE_2_0),
        "http://www.gnu.org/copyleft/lesser.html" to setOf(SpdxLicense.LGPL_3_0),
        "lgpl" to setOf(SpdxLicense.LGPL_2_1),
        "new BSD" to setOf(SpdxLicense.BSD_3_CLAUSE),
        "public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)"
                to setOf(SpdxLicense.PYTHON_2_0, SpdxLicense.BSD_2_CLAUSE, SpdxLicense.GPL_3_0),
        "ruby" to setOf(SpdxLicense.RUBY),
        "the Apache License, ASL Version 2.0" to setOf(SpdxLicense.APACHE_2_0),
        "wtfpl" to setOf(SpdxLicense.WTFPL),
        "zlib" to setOf(SpdxLicense.ZLIB)
    )

    fun map(license: String) = mapping[license] ?: emptySet()
}
