comment:
  # Keep this in sync with the number of codecov-action calls.
  after_n_builds: 4
coverage:
  status:
    project:
      default:
        threshold: 0.1%
flag_management:
  default_rules:
    carryforward: true
