# Commitlint configuration.
# See: https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md
---
rules:
  body-leading-blank:
    - 2
    - always
  body-max-line-length:
    - 2
    - always
    - 75
  footer-leading-blank:
    - 2
    - always
  header-max-length:
    - 2
    - always
    - 75
  scope-case:
    - 2
    - always
    - - camel-case
      - kebab-case
      - lower-case
      - pascal-case
      - snake-case
      - upper-case
  subject-case:
    - 2
    - always
    - - pascal-case
      - sentence-case
      - start-case
      - upper-case
  subject-empty:
    - 2
    - never
  subject-full-stop:
    - 2
    - never
    - .
  type-case:
    - 2
    - always
    - lower-case
  type-empty:
    - 2
    - never
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - deps
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
  signed-off-by:
    - 2
    - always
