#  Configuration for the markdownlint-cli2, see:
#  https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-yaml-example/.markdownlint-cli2.yaml

customRules:
  - markdownlint-rule-max-one-sentence-per-line
globs:
  - "**/*.md"
ignores:
  - "**/build/**"
  - "**/node_modules/**"
  - "**/projects/external/**"
  - "**/multi-kotlin-project/**"
  - "**/http4s-template/**"
  - "**/stack-yesodweb-simple/**"
