excludes:
  scopes:
  - name: "bench"
    reason: "TEST_TOOL_OF"
    comment: "Scope with dependencies only used for benchmarking. Not included in released artifacts in the context of this project."
  - name: "test"
    reason: "TEST_TOOL_OF"
    comment: "Scope with dependencies only used for testing. Not included in released artifacts in the context of this project."
