# This is an example for a (project specific) repository configuration file.
excludes:
  scopes:
  - pattern: "require-dev"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
