/*
 * Copyright (C) 2026 The ORT Project Copyright Holders <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package org.ossreviewtoolkit.plugins.packagemanagers.python

import io.kotest.assertions.throwables.shouldThrow
import io.kotest.core.spec.style.WordSpec
import io.kotest.engine.spec.tempdir
import io.kotest.matchers.collections.beEmpty
import io.kotest.matchers.collections.containExactly
import io.kotest.matchers.collections.haveSize
import io.kotest.matchers.nulls.beNull
import io.kotest.matchers.should
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain

import kotlinx.serialization.SerializationException

import net.peanuuutz.tomlkt.TomlTable

import org.ossreviewtoolkit.model.Hash
import org.ossreviewtoolkit.model.HashAlgorithm
import org.ossreviewtoolkit.utils.common.div

class PylockFileTest : WordSpec({
    "parsePylockFile()" should {
        "parse a lockfile written by uv" {
            val lockfile = tempdir() / "pylock.toml"

            // Inline tables with date-time values are what uv writes.
            lockfile.writeText(
                """
                    # This file was autogenerated by uv via the following command:
                    #    uv export --format pylock.toml -o pylock.toml
                    lock-version = "1.0"
                    created-by = "uv"
                    requires-python = ">=3.12"

                    [[packages]]
                    name = "attrs"
                    version = "26.1.0"
                    index = "https://pypi.org/simple"
                    sdist = { url = "https://files.pythonhosted.org/attrs-26.1.0.tar.gz", upload-time = 2026-03-19T14:22:25Z, size = 952055, hashes = { sha256 = "d03c" } }
                    wheels = [{ url = "https://files.pythonhosted.org/attrs-26.1.0-py3-none-any.whl", upload-time = 2026-03-19T14:22:23Z, size = 67548, hashes = { sha256 = "c647" } }]

                    [[packages]]
                    name = "colorama"
                    version = "0.4.6"
                    marker = "sys_platform == 'win32'"
                    index = "https://pypi.org/simple"
                    sdist = { url = "https://files.pythonhosted.org/colorama-0.4.6.tar.gz", upload-time = 2022-10-25T02:36:22Z, size = 27697, hashes = { sha256 = "0869" } }

                    [[packages]]
                    name = "pylock-sample"
                    directory = { path = ".", editable = true }
                """.trimIndent()
            )

            val pylock = parsePylockFile(lockfile)

            pylock.lockVersion shouldBe "1.0"
            pylock.createdBy shouldBe "uv"
            pylock.requiresPython shouldBe ">=3.12"
            pylock.packages should haveSize(3)

            with(pylock.packages[0]) {
                name shouldBe "attrs"
                version shouldBe "26.1.0"
                index shouldBe "https://pypi.org/simple"
                isIndexPackage shouldBe true
                sdist?.url shouldBe "https://files.pythonhosted.org/attrs-26.1.0.tar.gz"
                sdist?.hashes shouldBe mapOf("sha256" to "d03c")
                wheels.map { it.url } should
                    containExactly("https://files.pythonhosted.org/attrs-26.1.0-py3-none-any.whl")
            }

            with(pylock.packages[1]) {
                marker shouldBe "sys_platform == 'win32'"
                wheels should beEmpty()
            }

            with(pylock.packages[2]) {
                version should beNull()
                isIndexPackage shouldBe false
                directory?.path shouldBe "."
                directory?.editable shouldBe true
            }
        }

        "parse a lockfile written by pip" {
            val lockfile = tempdir() / "pylock.toml"

            // Arrays of tables in the long form are what pip writes.
            lockfile.writeText(
                """
                    lock-version = "1.0"
                    created-by = "pip"

                    [[packages]]
                    name = "attrs"
                    version = "26.1.0"

                    [[packages.wheels]]
                    name = "attrs-26.1.0-py3-none-any.whl"
                    url = "https://files.pythonhosted.org/attrs-26.1.0-py3-none-any.whl"

                    [packages.wheels.hashes]
                    sha256 = "c647"

                    [[packages]]
                    name = "pylock-sample"

                    [packages.directory]
                    path = "."
                """.trimIndent()
            )

            val pylock = parsePylockFile(lockfile)

            pylock.packages should haveSize(2)
            pylock.packages[0].wheels.single().name shouldBe "attrs-26.1.0-py3-none-any.whl"
            pylock.packages[0].wheels.single().hashes shouldBe mapOf("sha256" to "c647")
            pylock.packages[1].directory?.editable shouldBe false
        }

        "parse a lockfile written by PDM including its tool-specific tables" {
            val lockfile = tempdir() / "pylock.toml"

            lockfile.writeText(
                """
                    lock-version = "1.0"
                    requires-python = ">=3.12"
                    environments = [
                        "python_version >= \"3.12\"",
                    ]
                    extras = []
                    dependency-groups = ["default", "dev"]
                    default-groups = ["default"]
                    created-by = "pdm"
                    [[packages]]
                    name = "pluggy"
                    version = "1.6.0"
                    requires-python = ">=3.9"
                    sdist = {name = "pluggy-1.6.0.tar.gz", url = "https://files.pythonhosted.org/pluggy-1.6.0.tar.gz", hashes = {sha256 = "7dcc"}}
                    wheels = [
                        {name = "pluggy-1.6.0-py3-none-any.whl",url = "https://files.pythonhosted.org/pluggy-1.6.0-py3-none-any.whl",hashes = {sha256 = "e920"}},
                    ]
                    marker = "\"default\" in dependency_groups or \"dev\" in dependency_groups"

                    [packages.tool.pdm]
                    dependencies = []

                    [tool.pdm]
                    hashes = {sha256 = "1234"}
                    strategy = ["inherit_metadata", "static_urls"]

                    [[tool.pdm.targets]]
                    requires_python = ">=3.12"
                """.trimIndent()
            )

            val pylock = parsePylockFile(lockfile)

            pylock.environments should containExactly("python_version >= \"3.12\"")
            pylock.dependencyGroups should containExactly("default", "dev")
            pylock.defaultGroups should containExactly("default")
            pylock.packages.single().getGroupMembership() shouldBe
                GroupMembership(setOf("default", "dev"), isRequiredWithoutGroups = false)
        }

        "parse the example lockfile from PEP 751" {
            val lockfile = tempdir() / "pylock.toml"

            lockfile.writeText(
                """
                    lock-version = '1.0'
                    environments = ["sys_platform == 'win32'", "sys_platform == 'linux'"]
                    requires-python = '==3.12'
                    created-by = 'mousebender'

                    [[packages]]
                    name = 'attrs'
                    version = '25.1.0'
                    requires-python = '>=3.8'
                    wheels = [
                      {name = 'attrs-25.1.0-py3-none-any.whl', upload-time = 2025-01-25T11:30:10.164985+00:00, url = 'https://files.pythonhosted.org/attrs-25.1.0-py3-none-any.whl', size = 63152, hashes = {sha256 = 'c75a'}},
                    ]
                    [[packages.attestation-identities]]
                    environment = 'release-pypi'
                    kind = 'GitHub'
                    repository = 'python-attrs/attrs'
                    workflow = 'pypi-package.yml'

                    [[packages]]
                    name = 'cattrs'
                    version = '24.1.2'
                    requires-python = '>=3.8'
                    dependencies = [
                        {name = 'attrs'},
                    ]
                    wheels = [
                      {name = 'cattrs-24.1.2-py3-none-any.whl', upload-time = 2024-09-22T14:58:34.812643+00:00, url = 'https://files.pythonhosted.org/cattrs-24.1.2-py3-none-any.whl', size = 66446, hashes = {sha256 = '67c7'}},
                    ]

                    [tool.mousebender]
                    command = ['.', 'lock', '--platform', 'cpython3.12-windows-x64', 'cattrs', 'numpy']
                    run-on = 2025-03-06T12:28:57.760769
                """.trimIndent()
            )

            val pylock = parsePylockFile(lockfile)

            pylock.environments should haveSize(2)
            pylock.packages should haveSize(2)
            pylock.packages[1].dependencies.single() shouldBe TomlTable("name" to "attrs")
        }

        "parse VCS and archive entries" {
            val lockfile = tempdir() / "pylock.toml"

            lockfile.writeText(
                """
                    lock-version = "1.0"
                    created-by = "uv"

                    [[packages]]
                    name = "sampleproject"
                    version = "4.0.0"
                    vcs = { type = "git", url = "https://github.com/pypa/sampleproject", requested-revision = "main", commit-id = "621e4974ca25ce531773def586ba3ed8e736b3fc" }

                    [[packages]]
                    name = "six"
                    version = "1.17.0"
                    archive = { url = "https://files.pythonhosted.org/six-1.17.0-py2.py3-none-any.whl", hashes = { sha256 = "4721" } }
                """.trimIndent()
            )

            val pylock = parsePylockFile(lockfile)

            with(pylock.packages[0]) {
                isIndexPackage shouldBe false
                vcs?.type shouldBe "git"
                vcs?.url shouldBe "https://github.com/pypa/sampleproject"
                vcs?.requestedRevision shouldBe "main"
                vcs?.commitId shouldBe "621e4974ca25ce531773def586ba3ed8e736b3fc"
            }

            with(pylock.packages[1]) {
                isIndexPackage shouldBe false
                archive?.url shouldBe "https://files.pythonhosted.org/six-1.17.0-py2.py3-none-any.whl"
                archive?.hashes shouldBe mapOf("sha256" to "4721")
            }
        }

        "fail for an unsupported major version" {
            val lockfile = tempdir() / "pylock.toml"

            lockfile.writeText(
                """
                    lock-version = "2.0"
                    created-by = "future-tool"
                """.trimIndent()
            )

            val exception = shouldThrow<IllegalArgumentException> { parsePylockFile(lockfile) }

            exception.message shouldContain "lock-version '2.0'"
        }

        "fail for a lockfile that lacks a required key" {
            val lockfile = tempdir() / "pylock.toml"

            lockfile.writeText("lock-version = \"1.0\"\n")

            val exception = shouldThrow<SerializationException> { parsePylockFile(lockfile) }

            exception.message shouldContain "created-by"
        }

        "accept a lock-version without a minor part" {
            val lockfile = tempdir() / "pylock.toml"

            lockfile.writeText(
                """
                    lock-version = "1"
                    created-by = "some-tool"
                """.trimIndent()
            )

            parsePylockFile(lockfile).lockVersion shouldBe "1"
        }

        "accept a newer minor version" {
            val lockfile = tempdir() / "pylock.toml"

            lockfile.writeText(
                """
                    lock-version = "1.1"
                    created-by = "future-tool"
                    some-new-key = true
                """.trimIndent()
            )

            parsePylockFile(lockfile).lockVersion shouldBe "1.1"
        }
    }

    "normalizePythonPackageName()" should {
        "lower-case the name and replace runs of separators with a single dash" {
            "Typed___Ast".normalizePythonPackageName() shouldBe "typed-ast"
            "importlib.metadata".normalizePythonPackageName() shouldBe "importlib-metadata"
            "ruamel.yaml.clib".normalizePythonPackageName() shouldBe "ruamel-yaml-clib"
            "friendly-_.Bard".normalizePythonPackageName() shouldBe "friendly-bard"
        }
    }

    "Package.getGroupMembership()" should {
        fun membershipOf(marker: String) = PylockFile.Package(name = "pluggy", marker = marker).getGroupMembership()

        "return the groups from membership tests with either quoting style" {
            val membership = membershipOf(
                "\"default\" in dependency_groups and sys_platform == \"win32\" or 'dev' in dependency_groups"
            )

            membership shouldBe GroupMembership(setOf("default", "dev"), isRequiredWithoutGroups = false)
        }

        "treat a membership test for an extra like an environment condition" {
            // Extras are not modeled as scopes, so such a package is treated as required without any group.
            membershipOf("'yaml' in extras") shouldBe GroupMembership(emptySet(), isRequiredWithoutGroups = true)
        }

        "treat a negated membership test like an environment condition" {
            membershipOf("'dev' not in dependency_groups") shouldBe
                GroupMembership(emptySet(), isRequiredWithoutGroups = true)
        }

        "require a package without groups if one alternative of the marker names no group" {
            membershipOf("sys_platform == 'win32' or 'dev' in dependency_groups") shouldBe
                GroupMembership(setOf("dev"), isRequiredWithoutGroups = true)
        }

        "honor parentheses" {
            membershipOf(
                "(sys_platform == 'win32' or 'dev' in dependency_groups) and python_version >= '3.12'"
            ) shouldBe GroupMembership(setOf("dev"), isRequiredWithoutGroups = true)

            membershipOf("('a' in dependency_groups or 'b' in dependency_groups) and sys_platform == 'win32'") shouldBe
                GroupMembership(setOf("a", "b"), isRequiredWithoutGroups = false)
        }

        "not fail on a malformed marker" {
            val devOnly = GroupMembership(setOf("dev"), isRequiredWithoutGroups = false)

            membershipOf("('dev' in dependency_groups") shouldBe devOnly
            membershipOf("'dev' in dependency_groups) and") shouldBe devOnly
            membershipOf("") shouldBe GroupMembership(emptySet(), isRequiredWithoutGroups = true)
        }

        "require a package without a marker unconditionally" {
            PylockFile.Package(name = "pluggy").getGroupMembership() shouldBe
                GroupMembership(emptySet(), isRequiredWithoutGroups = true)
        }
    }

    "Package.isReferencedBy()" should {
        val entry = PylockFile.Package(
            name = "Typed_Ast",
            version = "1.5.5",
            marker = "sys_platform == 'win32'",
            vcs = PylockFile.Vcs(type = "git", url = "https://example.org/typed-ast", commitId = "621e")
        )

        "match the name in normalized form" {
            entry.isReferencedBy(TomlTable("name" to "typed-ast")) shouldBe true
            entry.isReferencedBy(TomlTable("name" to "typed-ast", "version" to "1.5.5")) shouldBe true
            entry.isReferencedBy(TomlTable("name" to "typed-ast", "version" to "1.5.4")) shouldBe false
        }

        "compare any other key of the reference" {
            entry.isReferencedBy(TomlTable("name" to "typed-ast", "marker" to "sys_platform == 'win32'")) shouldBe true
            entry.isReferencedBy(TomlTable("name" to "typed-ast", "marker" to "sys_platform == 'linux'")) shouldBe false
            entry.isReferencedBy(TomlTable("name" to "typed-ast", "index" to "https://pypi.org/simple")) shouldBe false
            entry.isReferencedBy(
                TomlTable(
                    "name" to "typed-ast",
                    "vcs" to mapOf("type" to "git", "url" to "https://example.org/typed-ast", "commit-id" to "621e")
                )
            ) shouldBe true
        }
    }

    "Map<String, String>.toHash()" should {
        "prefer the strongest known algorithm" {
            val hashes = mapOf(
                "md5" to "a".repeat(32),
                "sha256" to "b".repeat(64),
                "sha512" to "c".repeat(128),
                "blake2b" to "d".repeat(128)
            )

            hashes.toHash() shouldBe Hash("c".repeat(128), HashAlgorithm.SHA512)
        }

        "skip a malformed value in favor of the next algorithm" {
            val hashes = mapOf("sha256" to "b".repeat(64), "sha512" to "malformed")

            hashes.toHash() shouldBe Hash("b".repeat(64), HashAlgorithm.SHA256)
        }

        "return no hash if no algorithm is known" {
            mapOf("blake2b" to "d".repeat(128)).toHash() shouldBe Hash.NONE
        }
    }

    "Distribution" should {
        "derive the file name from the URL if it is not set" {
            val distribution = PylockFile.Distribution(
                url = "https://files.pythonhosted.org/a/b/attrs-25.1.0-py3-none-any.whl"
            )

            distribution.filename shouldBe "attrs-25.1.0-py3-none-any.whl"
            distribution.isUniversalWheel shouldBe true
        }

        "strip a query string and a fragment from the file name derived from the URL" {
            val distribution = PylockFile.Distribution(
                url = "https://index.example.org/dl/attrs-25.1.0-py3-none-any.whl?token=abc#sha256=c647"
            )

            distribution.filename shouldBe "attrs-25.1.0-py3-none-any.whl"
            distribution.isUniversalWheel shouldBe true
        }

        "recognize a platform-specific wheel" {
            val distribution = PylockFile.Distribution(name = "numpy-2.2.3-cp312-cp312-win_amd64.whl")

            distribution.isUniversalWheel shouldBe false
        }

        "convert to a remote artifact only if it has a URL" {
            PylockFile.Distribution(path = "wheels/attrs-25.1.0-py3-none-any.whl").toRemoteArtifact() should beNull()

            val artifact = PylockFile.Distribution(
                url = "https://example.org/a.whl",
                hashes = mapOf("sha256" to "c647".repeat(16))
            ).toRemoteArtifact()

            artifact?.url shouldBe "https://example.org/a.whl"
            artifact?.hash shouldBe Hash("c647".repeat(16), HashAlgorithm.SHA256)
        }
    }
})
