:title-page:
:sectnums:
:toc: preamble

=  Disclosure Document
:author-name: OSS Review Toolkit
:revdate: 1970-01-01
:revnumber: 1.0.0

== Acknowledgements
This software includes external packages and source code.
The applicable license information is listed below:

<<<

== Project Licenses

* License: <<MIT, MIT>>

** +Copyright 1+

<<<
== Dependencies

This software depends on external packages and source code.
The applicable license information is listed below:

*Dependency*

Package URL: _pkg:npm/%40ort/concluded-license@1.0_


The following licenses and copyrights were found in the source code of this package:


* License: <<MIT, MIT>>

** +Copyright 1+


* License: <<MIT WITH Libtool-exception, MIT WITH Libtool-exception>>

** No copyright found.

*Dependency*

Package URL: _pkg:npm/%40ort/declared-license@1.0_


The following licenses and copyrights were found in the source code of this package:


* License: <<BSD-3-Clause, BSD-3-Clause>>

** +Copyright 1+


* License: <<MIT, MIT>>

** No copyright found.

*Dependency*

Package URL: _pkg:npm/%40ort/license-file@1.0_


The following licenses and copyrights were found in the source code of this package:


* License: <<MIT, MIT>>

** +Copyright 1+
** +Copyright 2+

*Dependency*

Package URL: _pkg:npm/%40ort/license-file-and-additional-licenses@1.0_


The following licenses and copyrights were found in the source code of this package:


* License: <<BSD-3-Clause, BSD-3-Clause>>

** +Copyright 3+


* License: <<MIT, MIT>>

** +Copyright 1+
** +Copyright 2+

*Dependency*

Package URL: _pkg:npm/%40ort/no-license-file@1.0_


The following licenses and copyrights were found in the source code of this package:


* License: <<MIT, MIT>>

** +Copyright 1+

<<<
[appendix]
== License Texts

=== BSD-3-Clause

++++

Copyright 1
Copyright 3

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list
of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

Neither the name of the ORGANIZATION nor the names of its contributors may be
used to endorse or promote products derived from this software without specific
prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


++++
<<<
=== MIT

++++

Copyright 1
Copyright 2

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


++++
<<<
=== MIT WITH Libtool-exception

++++


Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.



As a special exception to the GNU General Public License,
if you distribute this file as part of a program or library that
is built using GNU Libtool, you may include this file under the
same distribution terms that you use for the rest of that program.


++++
<<<

== License Files for Packages






