/*
 * Copyright (C) 2017-2019 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package com.here.ort.analyzer

import com.here.ort.spdx.SpdxExpression
import com.here.ort.utils.DeclaredLicenseProcessor

import io.kotlintest.shouldNotBe
import io.kotlintest.specs.StringSpec

class DeclaredLicenseProcessorTest : StringSpec() {
    init {
        "Declared licenses can be processed" {
            val processor = DeclaredLicenseProcessor()

            declaredLicenses.forEach { declaredLicense ->
                println("Test '$declaredLicense'")
                val processedLicense = processor.processDeclaredLicense(declaredLicense)

                processedLicense shouldNotBe null
                processedLicense!!.validate(SpdxExpression.Strictness.ALLOW_DEPRECATED)
            }
        }
    }

    /**
     * A collection of declared license strings found in open source packages.
     */
    val declaredLicenses = listOf(
            "(EDL-1.0 OR EPL-1.0)",
            "(MIT-style) netCDF C library license",
            "2-clause BSD license",
            "2-clause BSDL",
            "3-Clause BSD",
            "3-Clause BSD License",
            "3-clause BSD",
            "AFLv2.1",
            "AL 2.0",
            "ALv2",
            "APL2",
            "APLv2.0",
            "ASF 2.0",
            "ASL",
            "ASL 2",
            "ASL 2.0",
            "ASL, version 2",
            "Academic Free License (AFL)",
            "Apache",
            "Apache  Version 2.0, January 2004",
            "Apache 2",
            "Apache 2.0",
            "Apache 2.0 License",
            "Apache License",
            "Apache License (2.0)",
            "Apache License 2",
            "Apache License 2.0",
            "Apache License V2.0",
            "Apache License Version 2",
            "Apache License Version 2.0",
            "Apache License v2",
            "Apache License v2.0",
            "Apache License, 2.0",
            "Apache License, V2.0 or later",
            "Apache License, Version 2",
            "Apache License, Version 2.0",
            """Apache License, Version 2.0 and
        Common Development And Distribution License (CDDL) Version 1.0 """.trimIndent(),
            "Apache License, version 2.0",
            "Apache License,Version 2.0",
            "Apache Public License 2.0",
            "Apache Software",
            "Apache Software License - Version 2.0",
            "Apache Software License 2.0",
            "Apache Software License, Version 1.1",
            "Apache Software License, version 1.1",
            "Apache Software License, version 2.0",
            "Apache Software Licenses",
            "Apache license",
            "Apache v2",
            "Apache v2.0",
            "Apache version 2.0",
            "Apache, Version 2.0",
            "Apache-2",
            """Apache-2.0 */ &#39; &quot; &#x3D;end --

 """.trimIndent(),
            "Apache2",
            "Artistic 2.0",
            "BOOST",
            "BSD",
            "BSD (3-clause)",
            "BSD - See ndg/httpsclient/LICENCE file for details",
            "BSD 2-Clause",
            "BSD 2-Clause License",
            "BSD 3 Clause",
            "BSD 3-Clause",
            "BSD 3-Clause \"New\" or \"Revised\" License (BSD-3-Clause)",
            "BSD 3-Clause License",
            "BSD 3-Clause license",
            "BSD 3-clause",
            "BSD Licence 3",
            "BSD License",
            "BSD License for HSQL",
            "BSD New",
            "BSD New license",
            "BSD licence",
            "BSD license",
            "BSD or Apache License, Version 2.0",
            "BSD style",
            "BSD style license",
            "BSD*",
            "BSD-3",
            "BSD-Style",
            "BSD-Style License",
            "BSD-like",
            "BSD-style",
            "BSD-style license",
            "BSD2",
            "BSD3",
            "Berkeley Software Distribution (BSD) License",
            "Bouncy Castle Licence",
            "Bouncy Castle License",
            "CC0",
            "CC0 1.0 Universal",
            "CC0 1.0 Universal License",
            "CDDL",
            "CDDL + GPLv2 with classpath exception",
            "CDDL 1.0",
            "CDDL 1.1",
            "CDDL License",
            "CDDL or GPL 2 with Classpath Exception",
            "CDDL or GPLv2 with exceptions",
            "CDDL v1.0 / GPL v2 dual license",
            "CDDL v1.1 / GPL v2 dual license",
            "CDDL+GPL",
            "CDDL+GPL License",
            "CDDL+GPLv2",
            "CDDL/GPLv2 dual license",
            "CDDL/GPLv2+CE",
            "COMMON DEVELOPMENT AND DISTRIBUTION LICENSE",
            "COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0",
            "CPL",
            "Cecill-C",
            "Common Development and Distribution License",
            "Common Development and Distribution License (CDDL) v1.0",
            "Common Development and Distribution License (CDDL), Version 1.1",
            "Common Public License - v 1.0",
            "Common Public License Version 1.0",
            "Creative Commons 3.0 BY-SA",
            "Dual License: CDDL 1.0 and GPL V2 with Classpath Exception",
            "Dual license consisting of the CDDL v1.1 and GPL v2",
            "EPL",
            "EPL (Eclipse Public License), V1.0 or later",
            "Eclipse Distribution License (EDL), Version 1.0",
            "Eclipse Distribution License (New BSD License)",
            "Eclipse Distribution License - v 1.0",
            "Eclipse Distribution License v. 1.0",
            "Eclipse Public License",
            "Eclipse Public License (EPL)",
            "Eclipse Public License (EPL) 1.0",
            "Eclipse Public License (EPL), Version 1.0",
            "Eclipse Public License - Version 1.0",
            "Eclipse Public License - v 1.0",
            "Eclipse Public License 1.0",
            "Eclipse Public License v1.0",
            "Eclipse Public License v2.0",
            "Eclipse Public License, Version 1.0",
            "Eclipse Publish License, Version 1.0",
            "FreeBSD",
            "GNU Affero General Public License v3",
            "GNU GENERAL PUBLIC LICENSE Version 2, June 1991",
            "GNU GPL v2",
            "GNU General Lesser Public License (LGPL) version 2.1",
            "GNU General Public Library",
            "GNU General Public License (GPL)",
            "GNU General Public License (GPL), version 2, with the Classpath exception",
            "GNU General Public License Version 2",
            "GNU General Public License v2 or later (GPLv2+)",
            "GNU General Public License v3 (GPLv3)",
            "GNU General Public License v3 or later (GPLv3+)",
            "GNU General Public License, Version 2 with the Classpath Exception",
            "GNU General Public License, Version 3",
            "GNU General Public License, version 2 (GPL2), with the classpath exception",
            "GNU General Public License, version 2, with the Classpath Exception",
            "GNU LESSER GENERAL PUBLIC LICENSE",
            "GNU LESSER GENERAL PUBLIC LICENSE V3.0",
            "GNU LESSER GENERAL PUBLIC LICENSE Version 2.1",
            "GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1",
            "GNU LGP (GNU General Public License), V2 or later",
            "GNU LGPL",
            "GNU LGPL (GNU Lesser General Public License), V2.1 or later",
            "GNU Lesser General Public Licence",
            "GNU Lesser General Public License",
            "GNU Lesser General Public License (LGPL)",
            "GNU Lesser General Public License (LGPL), Version 2.1",
            "GNU Lesser General Public License (LGPL), Version 3",
            "GNU Lesser General Public License 2.1",
            "GNU Lesser General Public License Version 2.1",
            "GNU Lesser General Public License Version 2.1, February 1999",
            "GNU Lesser General Public License v2 or later (LGPLv2+)",
            "GNU Lesser General Public License v3 (LGPLv3)",
            "GNU Lesser General Public License v3 or later (LGPLv3+)",
            "GNU Lesser General Public License v3+",
            "GNU Lesser General Public License, Version 2.1",
            "GNU Lesser General Public License, version 2.1",
            "GNU Lesser Public License",
            "GNU Library or Lesser General Public License (LGPL)",
            "GNU Public",
            "GPL",
            "GPL (with dual licensing option)",
            "GPL 3",
            "GPL v2 with ClassPath Exception",
            "GPL version 2",
            "GPL-2",
            "GPL2",
            "GPL2 w/ CPE",
            "GPLv2",
            "GPLv2+CE",
            "GPLv3",
            "HSQLDB License",
            "HSQLDB License, a BSD open source license",
            "ICU License",
            "ISC License (ISCL)",
            "ISC license",
            "ISC/BSD License",
            "Jython Software License",
            "Kirkk.com BSD License",
            "LGPL",
            "LGPL 2.1",
            "LGPL 3",
            "LGPL 3.0",
            "LGPL v3",
            "LGPL with exceptions or ZPL",
            "LGPL+BSD",
            "LGPL, version 2.1",
            "LGPL-3",
            "LGPL/MIT",
            "LGPL3",
            "LGPLv3",
            "LGPLv3 or later",
            "LGPLv3+",
            "Lesser General Public License (LGPL)",
            "Lesser General Public License, version 3 or greater",
            "License :: OSI Approved :: Apache Software",
            "License :: OSI Approved :: MIT",
            "License :: OSI Approved :: MIT License (http://opensource.org/licenses/MIT)",
            "License Agreement For Open Source Computer Vision Library (3-clause BSD License)",
            "MIT / http://rem.mit-license.org",
            "MIT Licence",
            "MIT License",
            "MIT licence",
            "MIT license",
            "MIT or GPLv3",
            "MIT, 2-clause BSD",
            "MIT-like",
            "MIT-style",
            "MIT/Expat",
            "MIT/X11",
            "MPL",
            "MPL 1.1",
            "MPL 2.0",
            "MPL 2.0 or EPL 1.0",
            "MPL 2.0, and EPL 1.0",
            "MPL v2",
            "MPLv2.0",
            "Mockrunner License, based on Apache Software License, version 1.1",
            "Mozilla Public License",
            "Mozilla Public License 1.1 (MPL 1.1)",
            "Mozilla Public License 2.0 (MPL 2.0)",
            "Mozilla Public License Version 1.0",
            "Mozilla Public License Version 1.1",
            "Mozilla Public License Version 2.0",
            "Mozilla Public License version 1.1",
            "Mozilla Public License version 2.0",
            "Mozilla Public License, Version 2.0",
            "Mozilla Public License, version 2.0",
            "NetBeans CDDL/GPL",
            "New BSD",
            "New BSD License",
            "New BSD license",
            "Perl Artistic v2",
            "Public Domain, per Creative Commons CC0",
            "Public domain (CC0-1.0)",
            "Python Software Foundation",
            "Ruby or LGPLv3+",
            "Ruby's",
            "Sleepycat License",
            "TMate Open Source License (with dual licensing option)",
            "The (New) BSD License",
            "The Apache License",
            "The Apache License, Version 2.0",
            "The Apache Software Licence, Version 2.0",
            "The Apache Software License, Version 2.0",
            "The Apache Software License, version 2.0",
            "The BSD 2-Clause License",
            "The BSD 3-Clause License",
            "The BSD License",
            "The BSD Software License",
            "The Eclipse Public License Version 1.0",
            "The GNU General Public License (GPL), Version 2, With Classpath Exception",
            "The GNU General Public License, Version 2",
            "The GNU Lesser General Public License, Version 2.1",
            "The JSON License",
            "The MIT",
            "The MIT License",
            "The MIT License (MIT)",
            "The MIT License(MIT)",
            "The MIT license",
            "The New BSD License",
            "The PostgreSQL License",
            "The SAX License",
            "The Unlicense",
            "The W3C License",
            "The W3C Software License",
            "Three-clause BSD-style",
            "Two-clause BSD-style license",
            "UNLICENSE",
            "UNLICENSED",
            "Unicode/ICU License",
            "ZPL 2.1",
            "Zope Public",
            "apache-2.0",
            "boost",
            "http://ant-contrib.sourceforge.net/tasks/LICENSE.txt",
            "http://opensource.org/licenses/MIT",
            "http://svnkit.com/license.html",
            "http://www.apache.org/licenses/LICENSE-2.0",
            "http://www.apache.org/licenses/LICENSE-2.0.txt",
            "http://www.gnu.org/copyleft/lesser.html",
            "lgpl",
            "new BSD",
            "public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)",
            "ruby",
            "the Apache License, ASL Version 2.0",
            "wtfpl",
            "zlib"
    )
}
