schema-version = "1.10.0"

[vars]
FLOX_DISABLE_METRICS = "true"

[options]
activate.mode = "run"
cuda-detection = false
systems = ["x86_64-linux"]

[install]
jdk25.pkg-path = "jdk25"
jdk25.outputs = "all"

# Required to run the Gradle wrapper:
coreutils.pkg-path = "coreutils"
coreutils.outputs = "all"
findutils.pkg-path = "findutils"
findutils.outputs = "all"
gnused.pkg-path = "gnused"
gnused.outputs = "all"
