schema-version = "1.10.0"

[vars]
FLOX_DISABLE_METRICS = "true"

[options]
activate.mode = "run"
cuda-detection = false
systems = ["x86_64-linux"]

[install]
jdk25.pkg-path = "jdk25"

# Required to run the Gradle wrapper:
coreutils.pkg-path = "coreutils"
findutils.pkg-path = "findutils"
gnused.pkg-path = "gnused"
