/*
 * Copyright (C) 2017-2019 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package com.here.ort.spdx

/**
 * An enum containing all SPDX license IDs. This class is generated by the Gradle task
 * 'generateSpdxLicenseEnum'.
 */
enum class SpdxLicense(
    /**
     * The id of the license.
     */
    val id: String,

    /**
     * Whether the [id] is deprecated or not.
     */
    val deprecated: Boolean = false
) {
    /** Attribution Assurance License */
    AAL("AAL"),
    /** Abstyles License */
    ABSTYLES("Abstyles"),
    /** Adobe Systems Incorporated Source Code License Agreement */
    ADOBE_2006("Adobe-2006"),
    /** Adobe Glyph List License */
    ADOBE_GLYPH("Adobe-Glyph"),
    /** Amazon Digital Services License */
    ADSL("ADSL"),
    /** Academic Free License v1.1 */
    AFL_1_1("AFL-1.1"),
    /** Academic Free License v1.2 */
    AFL_1_2("AFL-1.2"),
    /** Academic Free License v2.0 */
    AFL_2_0("AFL-2.0"),
    /** Academic Free License v2.1 */
    AFL_2_1("AFL-2.1"),
    /** Academic Free License v3.0 */
    AFL_3_0("AFL-3.0"),
    /** Afmparse License */
    AFMPARSE("Afmparse"),
    /** Affero General Public License v1.0 */
    AGPL_1_0("AGPL-1.0", true),
    /** Affero General Public License v1.0 only */
    AGPL_1_0_ONLY("AGPL-1.0-only"),
    /** Affero General Public License v1.0 or later */
    AGPL_1_0_OR_LATER("AGPL-1.0-or-later"),
    /** GNU Affero General Public License v3.0 */
    AGPL_3_0("AGPL-3.0", true),
    /** GNU Affero General Public License v3.0 only */
    AGPL_3_0_ONLY("AGPL-3.0-only"),
    /** GNU Affero General Public License v3.0 or later */
    AGPL_3_0_OR_LATER("AGPL-3.0-or-later"),
    /** Aladdin Free Public License */
    ALADDIN("Aladdin"),
    /** AMD's plpa_map.c License */
    AMDPLPA("AMDPLPA"),
    /** Apple MIT License */
    AML("AML"),
    /** Academy of Motion Picture Arts and Sciences BSD */
    AMPAS("AMPAS"),
    /** ANTLR Software Rights Notice */
    ANTLR_PD("ANTLR-PD"),
    /** Apache License 1.0 */
    APACHE_1_0("Apache-1.0"),
    /** Apache License 1.1 */
    APACHE_1_1("Apache-1.1"),
    /** Apache License 2.0 */
    APACHE_2_0("Apache-2.0"),
    /** Adobe Postscript AFM License */
    APAFML("APAFML"),
    /** Adaptive Public License 1.0 */
    APL_1_0("APL-1.0"),
    /** Apple Public Source License 1.0 */
    APSL_1_0("APSL-1.0"),
    /** Apple Public Source License 1.1 */
    APSL_1_1("APSL-1.1"),
    /** Apple Public Source License 1.2 */
    APSL_1_2("APSL-1.2"),
    /** Apple Public Source License 2.0 */
    APSL_2_0("APSL-2.0"),
    /** Artistic License 1.0 */
    ARTISTIC_1_0("Artistic-1.0"),
    /** Artistic License 1.0 w/clause 8 */
    ARTISTIC_1_0_CL8("Artistic-1.0-cl8"),
    /** Artistic License 1.0 (Perl) */
    ARTISTIC_1_0_PERL("Artistic-1.0-Perl"),
    /** Artistic License 2.0 */
    ARTISTIC_2_0("Artistic-2.0"),
    /** Bahyph License */
    BAHYPH("Bahyph"),
    /** Barr License */
    BARR("Barr"),
    /** Beerware License */
    BEERWARE("Beerware"),
    /** BitTorrent Open Source License v1.0 */
    BITTORRENT_1_0("BitTorrent-1.0"),
    /** BitTorrent Open Source License v1.1 */
    BITTORRENT_1_1("BitTorrent-1.1"),
    /** Borceux license */
    BORCEUX("Borceux"),
    /** BSD 1-Clause License */
    BSD_1_CLAUSE("BSD-1-Clause"),
    /** BSD 2-Clause "Simplified" License */
    BSD_2_CLAUSE("BSD-2-Clause"),
    /** BSD 2-Clause FreeBSD License */
    BSD_2_CLAUSE_FREEBSD("BSD-2-Clause-FreeBSD"),
    /** BSD 2-Clause NetBSD License */
    BSD_2_CLAUSE_NETBSD("BSD-2-Clause-NetBSD"),
    /** BSD-2-Clause Plus Patent License */
    BSD_2_CLAUSE_PATENT("BSD-2-Clause-Patent"),
    /** BSD 3-Clause "New" or "Revised" License */
    BSD_3_CLAUSE("BSD-3-Clause"),
    /** BSD with attribution */
    BSD_3_CLAUSE_ATTRIBUTION("BSD-3-Clause-Attribution"),
    /** BSD 3-Clause Clear License */
    BSD_3_CLAUSE_CLEAR("BSD-3-Clause-Clear"),
    /** Lawrence Berkeley National Labs BSD variant license */
    BSD_3_CLAUSE_LBNL("BSD-3-Clause-LBNL"),
    /** BSD 3-Clause No Nuclear License */
    BSD_3_CLAUSE_NO_NUCLEAR_LICENSE("BSD-3-Clause-No-Nuclear-License"),
    /** BSD 3-Clause No Nuclear License 2014 */
    BSD_3_CLAUSE_NO_NUCLEAR_LICENSE_2014("BSD-3-Clause-No-Nuclear-License-2014"),
    /** BSD 3-Clause No Nuclear Warranty */
    BSD_3_CLAUSE_NO_NUCLEAR_WARRANTY("BSD-3-Clause-No-Nuclear-Warranty"),
    /** BSD 4-Clause "Original" or "Old" License */
    BSD_4_CLAUSE("BSD-4-Clause"),
    /** BSD-4-Clause (University of California-Specific) */
    BSD_4_CLAUSE_UC("BSD-4-Clause-UC"),
    /** BSD Protection License */
    BSD_PROTECTION("BSD-Protection"),
    /** BSD Source Code Attribution */
    BSD_SOURCE_CODE("BSD-Source-Code"),
    /** Boost Software License 1.0 */
    BSL_1_0("BSL-1.0"),
    /** bzip2 and libbzip2 License v1.0.5 */
    BZIP2_1_0_5("bzip2-1.0.5"),
    /** bzip2 and libbzip2 License v1.0.6 */
    BZIP2_1_0_6("bzip2-1.0.6"),
    /** Caldera License */
    CALDERA("Caldera"),
    /** Computer Associates Trusted Open Source License 1.1 */
    CATOSL_1_1("CATOSL-1.1"),
    /** Creative Commons Zero v1.0 Universal */
    CC0_1_0("CC0-1.0"),
    /** Creative Commons Attribution 1.0 Generic */
    CC_BY_1_0("CC-BY-1.0"),
    /** Creative Commons Attribution 2.0 Generic */
    CC_BY_2_0("CC-BY-2.0"),
    /** Creative Commons Attribution 2.5 Generic */
    CC_BY_2_5("CC-BY-2.5"),
    /** Creative Commons Attribution 3.0 Unported */
    CC_BY_3_0("CC-BY-3.0"),
    /** Creative Commons Attribution 4.0 International */
    CC_BY_4_0("CC-BY-4.0"),
    /** Creative Commons Attribution Non Commercial 1.0 Generic */
    CC_BY_NC_1_0("CC-BY-NC-1.0"),
    /** Creative Commons Attribution Non Commercial 2.0 Generic */
    CC_BY_NC_2_0("CC-BY-NC-2.0"),
    /** Creative Commons Attribution Non Commercial 2.5 Generic */
    CC_BY_NC_2_5("CC-BY-NC-2.5"),
    /** Creative Commons Attribution Non Commercial 3.0 Unported */
    CC_BY_NC_3_0("CC-BY-NC-3.0"),
    /** Creative Commons Attribution Non Commercial 4.0 International */
    CC_BY_NC_4_0("CC-BY-NC-4.0"),
    /** Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic */
    CC_BY_NC_ND_1_0("CC-BY-NC-ND-1.0"),
    /** Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic */
    CC_BY_NC_ND_2_0("CC-BY-NC-ND-2.0"),
    /** Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic */
    CC_BY_NC_ND_2_5("CC-BY-NC-ND-2.5"),
    /** Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported */
    CC_BY_NC_ND_3_0("CC-BY-NC-ND-3.0"),
    /** Creative Commons Attribution Non Commercial No Derivatives 4.0 International */
    CC_BY_NC_ND_4_0("CC-BY-NC-ND-4.0"),
    /** Creative Commons Attribution Non Commercial Share Alike 1.0 Generic */
    CC_BY_NC_SA_1_0("CC-BY-NC-SA-1.0"),
    /** Creative Commons Attribution Non Commercial Share Alike 2.0 Generic */
    CC_BY_NC_SA_2_0("CC-BY-NC-SA-2.0"),
    /** Creative Commons Attribution Non Commercial Share Alike 2.5 Generic */
    CC_BY_NC_SA_2_5("CC-BY-NC-SA-2.5"),
    /** Creative Commons Attribution Non Commercial Share Alike 3.0 Unported */
    CC_BY_NC_SA_3_0("CC-BY-NC-SA-3.0"),
    /** Creative Commons Attribution Non Commercial Share Alike 4.0 International */
    CC_BY_NC_SA_4_0("CC-BY-NC-SA-4.0"),
    /** Creative Commons Attribution No Derivatives 1.0 Generic */
    CC_BY_ND_1_0("CC-BY-ND-1.0"),
    /** Creative Commons Attribution No Derivatives 2.0 Generic */
    CC_BY_ND_2_0("CC-BY-ND-2.0"),
    /** Creative Commons Attribution No Derivatives 2.5 Generic */
    CC_BY_ND_2_5("CC-BY-ND-2.5"),
    /** Creative Commons Attribution No Derivatives 3.0 Unported */
    CC_BY_ND_3_0("CC-BY-ND-3.0"),
    /** Creative Commons Attribution No Derivatives 4.0 International */
    CC_BY_ND_4_0("CC-BY-ND-4.0"),
    /** Creative Commons Attribution Share Alike 1.0 Generic */
    CC_BY_SA_1_0("CC-BY-SA-1.0"),
    /** Creative Commons Attribution Share Alike 2.0 Generic */
    CC_BY_SA_2_0("CC-BY-SA-2.0"),
    /** Creative Commons Attribution Share Alike 2.5 Generic */
    CC_BY_SA_2_5("CC-BY-SA-2.5"),
    /** Creative Commons Attribution Share Alike 3.0 Unported */
    CC_BY_SA_3_0("CC-BY-SA-3.0"),
    /** Creative Commons Attribution Share Alike 4.0 International */
    CC_BY_SA_4_0("CC-BY-SA-4.0"),
    /** Common Development and Distribution License 1.0 */
    CDDL_1_0("CDDL-1.0"),
    /** Common Development and Distribution License 1.1 */
    CDDL_1_1("CDDL-1.1"),
    /** Community Data License Agreement Permissive 1.0 */
    CDLA_PERMISSIVE_1_0("CDLA-Permissive-1.0"),
    /** Community Data License Agreement Sharing 1.0 */
    CDLA_SHARING_1_0("CDLA-Sharing-1.0"),
    /** CeCILL Free Software License Agreement v1.0 */
    CECILL_1_0("CECILL-1.0"),
    /** CeCILL Free Software License Agreement v1.1 */
    CECILL_1_1("CECILL-1.1"),
    /** CeCILL Free Software License Agreement v2.0 */
    CECILL_2_0("CECILL-2.0"),
    /** CeCILL Free Software License Agreement v2.1 */
    CECILL_2_1("CECILL-2.1"),
    /** CeCILL-B Free Software License Agreement */
    CECILL_B("CECILL-B"),
    /** CeCILL-C Free Software License Agreement */
    CECILL_C("CECILL-C"),
    /** CERN Open Hardware License v1.1 */
    CERN_OHL_1_1("CERN-OHL-1.1"),
    /** CERN Open Hardware Licence v1.2 */
    CERN_OHL_1_2("CERN-OHL-1.2"),
    /** Clarified Artistic License */
    CLARTISTIC("ClArtistic"),
    /** CNRI Jython License */
    CNRI_JYTHON("CNRI-Jython"),
    /** CNRI Python License */
    CNRI_PYTHON("CNRI-Python"),
    /** CNRI Python Open Source GPL Compatible License Agreement */
    CNRI_PYTHON_GPL_COMPATIBLE("CNRI-Python-GPL-Compatible"),
    /** Condor Public License v1.1 */
    CONDOR_1_1("Condor-1.1"),
    /** copyleft-next 0.3.0 */
    COPYLEFT_NEXT_0_3_0("copyleft-next-0.3.0"),
    /** copyleft-next 0.3.1 */
    COPYLEFT_NEXT_0_3_1("copyleft-next-0.3.1"),
    /** Common Public Attribution License 1.0 */
    CPAL_1_0("CPAL-1.0"),
    /** Common Public License 1.0 */
    CPL_1_0("CPL-1.0"),
    /** Code Project Open License 1.02 */
    CPOL_1_02("CPOL-1.02"),
    /** Crossword License */
    CROSSWORD("Crossword"),
    /** CrystalStacker License */
    CRYSTALSTACKER("CrystalStacker"),
    /** CUA Office Public License v1.0 */
    CUA_OPL_1_0("CUA-OPL-1.0"),
    /** Cube License */
    CUBE("Cube"),
    /** curl License */
    CURL("curl"),
    /** diffmark license */
    DIFFMARK("diffmark"),
    /** DOC License */
    DOC("DOC"),
    /** Dotseqn License */
    DOTSEQN("Dotseqn"),
    /** DSDP License */
    DSDP("DSDP"),
    /** dvipdfm License */
    DVIPDFM("dvipdfm"),
    /** Deutsche Freie Software Lizenz */
    D_FSL_1_0("D-FSL-1.0"),
    /** Educational Community License v1.0 */
    ECL_1_0("ECL-1.0"),
    /** Educational Community License v2.0 */
    ECL_2_0("ECL-2.0"),
    /** eCos license version 2.0 */
    ECOS_2_0("eCos-2.0", true),
    /** Eiffel Forum License v1.0 */
    EFL_1_0("EFL-1.0"),
    /** Eiffel Forum License v2.0 */
    EFL_2_0("EFL-2.0"),
    /** eGenix.com Public License 1.1.0 */
    EGENIX("eGenix"),
    /** Entessa Public License v1.0 */
    ENTESSA("Entessa"),
    /** Eclipse Public License 1.0 */
    EPL_1_0("EPL-1.0"),
    /** Eclipse Public License 2.0 */
    EPL_2_0("EPL-2.0"),
    /** Erlang Public License v1.1 */
    ERLPL_1_1("ErlPL-1.1"),
    /** EU DataGrid Software License */
    EUDATAGRID("EUDatagrid"),
    /** European Union Public License 1.0 */
    EUPL_1_0("EUPL-1.0"),
    /** European Union Public License 1.1 */
    EUPL_1_1("EUPL-1.1"),
    /** European Union Public License 1.2 */
    EUPL_1_2("EUPL-1.2"),
    /** Eurosym License */
    EUROSYM("Eurosym"),
    /** Fair License */
    FAIR("Fair"),
    /** Frameworx Open License 1.0 */
    FRAMEWORX_1_0("Frameworx-1.0"),
    /** FreeImage Public License v1.0 */
    FREEIMAGE("FreeImage"),
    /** FSF All Permissive License */
    FSFAP("FSFAP"),
    /** FSF Unlimited License */
    FSFUL("FSFUL"),
    /** FSF Unlimited License (with License Retention) */
    FSFULLR("FSFULLR"),
    /** Freetype Project License */
    FTL("FTL"),
    /** GNU Free Documentation License v1.1 */
    GFDL_1_1("GFDL-1.1", true),
    /** GNU Free Documentation License v1.1 only */
    GFDL_1_1_ONLY("GFDL-1.1-only"),
    /** GNU Free Documentation License v1.1 or later */
    GFDL_1_1_OR_LATER("GFDL-1.1-or-later"),
    /** GNU Free Documentation License v1.2 */
    GFDL_1_2("GFDL-1.2", true),
    /** GNU Free Documentation License v1.2 only */
    GFDL_1_2_ONLY("GFDL-1.2-only"),
    /** GNU Free Documentation License v1.2 or later */
    GFDL_1_2_OR_LATER("GFDL-1.2-or-later"),
    /** GNU Free Documentation License v1.3 */
    GFDL_1_3("GFDL-1.3", true),
    /** GNU Free Documentation License v1.3 only */
    GFDL_1_3_ONLY("GFDL-1.3-only"),
    /** GNU Free Documentation License v1.3 or later */
    GFDL_1_3_OR_LATER("GFDL-1.3-or-later"),
    /** Giftware License */
    GIFTWARE("Giftware"),
    /** GL2PS License */
    GL2PS("GL2PS"),
    /** 3dfx Glide License */
    GLIDE("Glide"),
    /** Glulxe License */
    GLULXE("Glulxe"),
    /** gnuplot License */
    GNUPLOT("gnuplot"),
    /** GNU General Public License v1.0 only */
    GPL_1_0("GPL-1.0", true),
    /** GNU General Public License v1.0 or later */
    GPL_1_0PLUS("GPL-1.0+", true),
    /** GNU General Public License v1.0 only */
    GPL_1_0_ONLY("GPL-1.0-only"),
    /** GNU General Public License v1.0 or later */
    GPL_1_0_OR_LATER("GPL-1.0-or-later"),
    /** GNU General Public License v2.0 only */
    GPL_2_0("GPL-2.0", true),
    /** GNU General Public License v2.0 or later */
    GPL_2_0PLUS("GPL-2.0+", true),
    /** GNU General Public License v2.0 only */
    GPL_2_0_ONLY("GPL-2.0-only"),
    /** GNU General Public License v2.0 or later */
    GPL_2_0_OR_LATER("GPL-2.0-or-later"),
    /** GNU General Public License v2.0 w/Autoconf exception */
    GPL_2_0_WITH_AUTOCONF_EXCEPTION("GPL-2.0-with-autoconf-exception", true),
    /** GNU General Public License v2.0 w/Bison exception */
    GPL_2_0_WITH_BISON_EXCEPTION("GPL-2.0-with-bison-exception", true),
    /** GNU General Public License v2.0 w/Classpath exception */
    GPL_2_0_WITH_CLASSPATH_EXCEPTION("GPL-2.0-with-classpath-exception", true),
    /** GNU General Public License v2.0 w/Font exception */
    GPL_2_0_WITH_FONT_EXCEPTION("GPL-2.0-with-font-exception", true),
    /** GNU General Public License v2.0 w/GCC Runtime Library exception */
    GPL_2_0_WITH_GCC_EXCEPTION("GPL-2.0-with-GCC-exception", true),
    /** GNU General Public License v3.0 only */
    GPL_3_0("GPL-3.0", true),
    /** GNU General Public License v3.0 or later */
    GPL_3_0PLUS("GPL-3.0+", true),
    /** GNU General Public License v3.0 only */
    GPL_3_0_ONLY("GPL-3.0-only"),
    /** GNU General Public License v3.0 or later */
    GPL_3_0_OR_LATER("GPL-3.0-or-later"),
    /** GNU General Public License v3.0 w/Autoconf exception */
    GPL_3_0_WITH_AUTOCONF_EXCEPTION("GPL-3.0-with-autoconf-exception", true),
    /** GNU General Public License v3.0 w/GCC Runtime Library exception */
    GPL_3_0_WITH_GCC_EXCEPTION("GPL-3.0-with-GCC-exception", true),
    /** gSOAP Public License v1.3b */
    GSOAP_1_3B("gSOAP-1.3b"),
    /** Haskell Language Report License */
    HASKELLREPORT("HaskellReport"),
    /** Historical Permission Notice and Disclaimer */
    HPND("HPND"),
    /** Historical Permission Notice and Disclaimer - sell variant */
    HPND_SELL_VARIANT("HPND-sell-variant"),
    /** IBM PowerPC Initialization and Boot Software */
    IBM_PIBS("IBM-pibs"),
    /** ICU License */
    ICU("ICU"),
    /** Independent JPEG Group License */
    IJG("IJG"),
    /** ImageMagick License */
    IMAGEMAGICK("ImageMagick"),
    /** iMatix Standard Function Library Agreement */
    IMATIX("iMatix"),
    /** Imlib2 License */
    IMLIB2("Imlib2"),
    /** Info-ZIP License */
    INFO_ZIP("Info-ZIP"),
    /** Intel Open Source License */
    INTEL("Intel"),
    /** Intel ACPI Software License Agreement */
    INTEL_ACPI("Intel-ACPI"),
    /** Interbase Public License v1.0 */
    INTERBASE_1_0("Interbase-1.0"),
    /** IPA Font License */
    IPA("IPA"),
    /** IBM Public License v1.0 */
    IPL_1_0("IPL-1.0"),
    /** ISC License */
    ISC("ISC"),
    /** JasPer License */
    JASPER_2_0("JasPer-2.0"),
    /** Japan Network Information Center License */
    JPNIC("JPNIC"),
    /** JSON License */
    JSON("JSON"),
    /** Licence Art Libre 1.2 */
    LAL_1_2("LAL-1.2"),
    /** Licence Art Libre 1.3 */
    LAL_1_3("LAL-1.3"),
    /** Latex2e License */
    LATEX2E("Latex2e"),
    /** Leptonica License */
    LEPTONICA("Leptonica"),
    /** Lesser General Public License For Linguistic Resources */
    LGPLLR("LGPLLR"),
    /** GNU Library General Public License v2 only */
    LGPL_2_0("LGPL-2.0", true),
    /** GNU Library General Public License v2 or later */
    LGPL_2_0PLUS("LGPL-2.0+", true),
    /** GNU Library General Public License v2 only */
    LGPL_2_0_ONLY("LGPL-2.0-only"),
    /** GNU Library General Public License v2 or later */
    LGPL_2_0_OR_LATER("LGPL-2.0-or-later"),
    /** GNU Lesser General Public License v2.1 only */
    LGPL_2_1("LGPL-2.1", true),
    /** GNU Library General Public License v2.1 or later */
    LGPL_2_1PLUS("LGPL-2.1+", true),
    /** GNU Lesser General Public License v2.1 only */
    LGPL_2_1_ONLY("LGPL-2.1-only"),
    /** GNU Lesser General Public License v2.1 or later */
    LGPL_2_1_OR_LATER("LGPL-2.1-or-later"),
    /** GNU Lesser General Public License v3.0 only */
    LGPL_3_0("LGPL-3.0", true),
    /** GNU Lesser General Public License v3.0 or later */
    LGPL_3_0PLUS("LGPL-3.0+", true),
    /** GNU Lesser General Public License v3.0 only */
    LGPL_3_0_ONLY("LGPL-3.0-only"),
    /** GNU Lesser General Public License v3.0 or later */
    LGPL_3_0_OR_LATER("LGPL-3.0-or-later"),
    /** libpng License */
    LIBPNG("Libpng"),
    /** PNG Reference Library version 2 */
    LIBPNG_2_0("libpng-2.0"),
    /** libtiff License */
    LIBTIFF("libtiff"),
    /** Licence Libre du Québec – Permissive version 1.1 */
    LILIQ_P_1_1("LiLiQ-P-1.1"),
    /** Licence Libre du Québec – Réciprocité forte version 1.1 */
    LILIQ_RPLUS_1_1("LiLiQ-Rplus-1.1"),
    /** Licence Libre du Québec – Réciprocité version 1.1 */
    LILIQ_R_1_1("LiLiQ-R-1.1"),
    /** Linux Kernel Variant of OpenIB.org license */
    LINUX_OPENIB("Linux-OpenIB"),
    /** Lucent Public License Version 1.0 */
    LPL_1_0("LPL-1.0"),
    /** Lucent Public License v1.02 */
    LPL_1_02("LPL-1.02"),
    /** LaTeX Project Public License v1.0 */
    LPPL_1_0("LPPL-1.0"),
    /** LaTeX Project Public License v1.1 */
    LPPL_1_1("LPPL-1.1"),
    /** LaTeX Project Public License v1.2 */
    LPPL_1_2("LPPL-1.2"),
    /** LaTeX Project Public License v1.3a */
    LPPL_1_3A("LPPL-1.3a"),
    /** LaTeX Project Public License v1.3c */
    LPPL_1_3C("LPPL-1.3c"),
    /** MakeIndex License */
    MAKEINDEX("MakeIndex"),
    /** MirOS License */
    MIROS("MirOS"),
    /** MIT License */
    MIT("MIT"),
    /** MIT +no-false-attribs license */
    MITNFA("MITNFA"),
    /** MIT No Attribution */
    MIT_0("MIT-0"),
    /** Enlightenment License (e16) */
    MIT_ADVERTISING("MIT-advertising"),
    /** CMU License */
    MIT_CMU("MIT-CMU"),
    /** enna License */
    MIT_ENNA("MIT-enna"),
    /** feh License */
    MIT_FEH("MIT-feh"),
    /** Motosoto License */
    MOTOSOTO("Motosoto"),
    /** mpich2 License */
    MPICH2("mpich2"),
    /** Mozilla Public License 1.0 */
    MPL_1_0("MPL-1.0"),
    /** Mozilla Public License 1.1 */
    MPL_1_1("MPL-1.1"),
    /** Mozilla Public License 2.0 */
    MPL_2_0("MPL-2.0"),
    /** Mozilla Public License 2.0 (no copyleft exception) */
    MPL_2_0_NO_COPYLEFT_EXCEPTION("MPL-2.0-no-copyleft-exception"),
    /** Microsoft Public License */
    MS_PL("MS-PL"),
    /** Microsoft Reciprocal License */
    MS_RL("MS-RL"),
    /** Matrix Template Library License */
    MTLL("MTLL"),
    /** Multics License */
    MULTICS("Multics"),
    /** Mup License */
    MUP("Mup"),
    /** NASA Open Source Agreement 1.3 */
    NASA_1_3("NASA-1.3"),
    /** Naumen Public License */
    NAUMEN("Naumen"),
    /** Net Boolean Public License v1 */
    NBPL_1_0("NBPL-1.0"),
    /** University of Illinois/NCSA Open Source License */
    NCSA("NCSA"),
    /** NetCDF license */
    NETCDF("NetCDF"),
    /** Net-SNMP License */
    NET_SNMP("Net-SNMP"),
    /** Newsletr License */
    NEWSLETR("Newsletr"),
    /** Nethack General Public License */
    NGPL("NGPL"),
    /** Norwegian Licence for Open Government Data */
    NLOD_1_0("NLOD-1.0"),
    /** No Limit Public License */
    NLPL("NLPL"),
    /** Nokia Open Source License */
    NOKIA("Nokia"),
    /** Netizen Open Source License */
    NOSL("NOSL"),
    /** Noweb License */
    NOWEB("Noweb"),
    /** Netscape Public License v1.0 */
    NPL_1_0("NPL-1.0"),
    /** Netscape Public License v1.1 */
    NPL_1_1("NPL-1.1"),
    /** Non-Profit Open Software License 3.0 */
    NPOSL_3_0("NPOSL-3.0"),
    /** NRL License */
    NRL("NRL"),
    /** NTP License */
    NTP("NTP"),
    /** Nunit License */
    NUNIT("Nunit", true),
    /** Open CASCADE Technology Public License */
    OCCT_PL("OCCT-PL"),
    /** OCLC Research Public License 2.0 */
    OCLC_2_0("OCLC-2.0"),
    /** ODC Open Database License v1.0 */
    ODBL_1_0("ODbL-1.0"),
    /** Open Data Commons Attribution License v1.0 */
    ODC_BY_1_0("ODC-By-1.0"),
    /** SIL Open Font License 1.0 */
    OFL_1_0("OFL-1.0"),
    /** SIL Open Font License 1.1 */
    OFL_1_1("OFL-1.1"),
    /** Open Government Licence v1.0 */
    OGL_UK_1_0("OGL-UK-1.0"),
    /** Open Government Licence v2.0 */
    OGL_UK_2_0("OGL-UK-2.0"),
    /** Open Government Licence v3.0 */
    OGL_UK_3_0("OGL-UK-3.0"),
    /** Open Group Test Suite License */
    OGTSL("OGTSL"),
    /** Open LDAP Public License v1.1 */
    OLDAP_1_1("OLDAP-1.1"),
    /** Open LDAP Public License v1.2 */
    OLDAP_1_2("OLDAP-1.2"),
    /** Open LDAP Public License v1.3 */
    OLDAP_1_3("OLDAP-1.3"),
    /** Open LDAP Public License v1.4 */
    OLDAP_1_4("OLDAP-1.4"),
    /** Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B) */
    OLDAP_2_0("OLDAP-2.0"),
    /** Open LDAP Public License v2.0.1 */
    OLDAP_2_0_1("OLDAP-2.0.1"),
    /** Open LDAP Public License v2.1 */
    OLDAP_2_1("OLDAP-2.1"),
    /** Open LDAP Public License v2.2 */
    OLDAP_2_2("OLDAP-2.2"),
    /** Open LDAP Public License v2.2.1 */
    OLDAP_2_2_1("OLDAP-2.2.1"),
    /** Open LDAP Public License 2.2.2 */
    OLDAP_2_2_2("OLDAP-2.2.2"),
    /** Open LDAP Public License v2.3 */
    OLDAP_2_3("OLDAP-2.3"),
    /** Open LDAP Public License v2.4 */
    OLDAP_2_4("OLDAP-2.4"),
    /** Open LDAP Public License v2.5 */
    OLDAP_2_5("OLDAP-2.5"),
    /** Open LDAP Public License v2.6 */
    OLDAP_2_6("OLDAP-2.6"),
    /** Open LDAP Public License v2.7 */
    OLDAP_2_7("OLDAP-2.7"),
    /** Open LDAP Public License v2.8 */
    OLDAP_2_8("OLDAP-2.8"),
    /** Open Market License */
    OML("OML"),
    /** OpenSSL License */
    OPENSSL("OpenSSL"),
    /** Open Public License v1.0 */
    OPL_1_0("OPL-1.0"),
    /** OSET Public License version 2.1 */
    OSET_PL_2_1("OSET-PL-2.1"),
    /** Open Software License 1.0 */
    OSL_1_0("OSL-1.0"),
    /** Open Software License 1.1 */
    OSL_1_1("OSL-1.1"),
    /** Open Software License 2.0 */
    OSL_2_0("OSL-2.0"),
    /** Open Software License 2.1 */
    OSL_2_1("OSL-2.1"),
    /** Open Software License 3.0 */
    OSL_3_0("OSL-3.0"),
    /** ODC Public Domain Dedication & License 1.0 */
    PDDL_1_0("PDDL-1.0"),
    /** PHP License v3.0 */
    PHP_3_0("PHP-3.0"),
    /** PHP License v3.01 */
    PHP_3_01("PHP-3.01"),
    /** Plexus Classworlds License */
    PLEXUS("Plexus"),
    /** PostgreSQL License */
    POSTGRESQL("PostgreSQL"),
    /** psfrag License */
    PSFRAG("psfrag"),
    /** psutils License */
    PSUTILS("psutils"),
    /** Python License 2.0 */
    PYTHON_2_0("Python-2.0"),
    /** Qhull License */
    QHULL("Qhull"),
    /** Q Public License 1.0 */
    QPL_1_0("QPL-1.0"),
    /** Rdisc License */
    RDISC("Rdisc"),
    /** Red Hat eCos Public License v1.1 */
    RHECOS_1_1("RHeCos-1.1"),
    /** Reciprocal Public License 1.1 */
    RPL_1_1("RPL-1.1"),
    /** Reciprocal Public License 1.5 */
    RPL_1_5("RPL-1.5"),
    /** RealNetworks Public Source License v1.0 */
    RPSL_1_0("RPSL-1.0"),
    /** RSA Message-Digest License  */
    RSA_MD("RSA-MD"),
    /** Ricoh Source Code Public License */
    RSCPL("RSCPL"),
    /** Ruby License */
    RUBY("Ruby"),
    /** Saxpath License */
    SAXPATH("Saxpath"),
    /** Sax Public Domain Notice */
    SAX_PD("SAX-PD"),
    /** SCEA Shared Source License */
    SCEA("SCEA"),
    /** Sendmail License */
    SENDMAIL("Sendmail"),
    /** Sendmail License 8.23 */
    SENDMAIL_8_23("Sendmail-8.23"),
    /** SGI Free Software License B v1.0 */
    SGI_B_1_0("SGI-B-1.0"),
    /** SGI Free Software License B v1.1 */
    SGI_B_1_1("SGI-B-1.1"),
    /** SGI Free Software License B v2.0 */
    SGI_B_2_0("SGI-B-2.0"),
    /** Simple Public License 2.0 */
    SIMPL_2_0("SimPL-2.0"),
    /** Sun Industry Standards Source License v1.1 */
    SISSL("SISSL"),
    /** Sun Industry Standards Source License v1.2 */
    SISSL_1_2("SISSL-1.2"),
    /** Sleepycat License */
    SLEEPYCAT("Sleepycat"),
    /** Standard ML of New Jersey License */
    SMLNJ("SMLNJ"),
    /** Secure Messaging Protocol Public License */
    SMPPL("SMPPL"),
    /** SNIA Public License 1.1 */
    SNIA("SNIA"),
    /** Spencer License 86 */
    SPENCER_86("Spencer-86"),
    /** Spencer License 94 */
    SPENCER_94("Spencer-94"),
    /** Spencer License 99 */
    SPENCER_99("Spencer-99"),
    /** Sun Public License v1.0 */
    SPL_1_0("SPL-1.0"),
    /** Standard ML of New Jersey License */
    STANDARDML_NJ("StandardML-NJ", true),
    /** SugarCRM Public License v1.1.3 */
    SUGARCRM_1_1_3("SugarCRM-1.1.3"),
    /** Scheme Widget Library (SWL) Software License Agreement */
    SWL("SWL"),
    /** TAPR Open Hardware License v1.0 */
    TAPR_OHL_1_0("TAPR-OHL-1.0"),
    /** TCL/TK License */
    TCL("TCL"),
    /** TCP Wrappers License */
    TCP_WRAPPERS("TCP-wrappers"),
    /** TMate Open Source License */
    TMATE("TMate"),
    /** TORQUE v2.5+ Software License v1.1 */
    TORQUE_1_1("TORQUE-1.1"),
    /** Trusster Open Source License */
    TOSL("TOSL"),
    /** Technische Universitaet Berlin License 1.0 */
    TU_BERLIN_1_0("TU-Berlin-1.0"),
    /** Technische Universitaet Berlin License 2.0 */
    TU_BERLIN_2_0("TU-Berlin-2.0"),
    /** Unicode License Agreement - Data Files and Software (2015) */
    UNICODE_DFS_2015("Unicode-DFS-2015"),
    /** Unicode License Agreement - Data Files and Software (2016) */
    UNICODE_DFS_2016("Unicode-DFS-2016"),
    /** Unicode Terms of Use */
    UNICODE_TOU("Unicode-TOU"),
    /** The Unlicense */
    UNLICENSE("Unlicense"),
    /** Universal Permissive License v1.0 */
    UPL_1_0("UPL-1.0"),
    /** Vim License */
    VIM("Vim"),
    /** VOSTROM Public License for Open Source */
    VOSTROM("VOSTROM"),
    /** Vovida Software License v1.0 */
    VSL_1_0("VSL-1.0"),
    /** W3C Software Notice and License (2002-12-31) */
    W3C("W3C"),
    /** W3C Software Notice and License (1998-07-20) */
    W3C_19980720("W3C-19980720"),
    /** W3C Software Notice and Document License (2015-05-13) */
    W3C_20150513("W3C-20150513"),
    /** Sybase Open Watcom Public License 1.0 */
    WATCOM_1_0("Watcom-1.0"),
    /** Wsuipa License */
    WSUIPA("Wsuipa"),
    /** Do What The F*ck You Want To Public License */
    WTFPL("WTFPL"),
    /** wxWindows Library License */
    WXWINDOWS("wxWindows", true),
    /** X11 License */
    X11("X11"),
    /** Xerox License */
    XEROX("Xerox"),
    /** XFree86 License 1.1 */
    XFREE86_1_1("XFree86-1.1"),
    /** xinetd License */
    XINETD("xinetd"),
    /** X.Net License */
    XNET("Xnet"),
    /** XPP License */
    XPP("xpp"),
    /** XSkat License */
    XSKAT("XSkat"),
    /** Yahoo! Public License v1.0 */
    YPL_1_0("YPL-1.0"),
    /** Yahoo! Public License v1.1 */
    YPL_1_1("YPL-1.1"),
    /** Zed License */
    ZED("Zed"),
    /** Zend License v2.0 */
    ZEND_2_0("Zend-2.0"),
    /** Zimbra Public License v1.3 */
    ZIMBRA_1_3("Zimbra-1.3"),
    /** Zimbra Public License v1.4 */
    ZIMBRA_1_4("Zimbra-1.4"),
    /** zlib License */
    ZLIB("Zlib"),
    /** zlib/libpng License with Acknowledgement */
    ZLIB_ACKNOWLEDGEMENT("zlib-acknowledgement"),
    /** Zope Public License 1.1 */
    ZPL_1_1("ZPL-1.1"),
    /** Zope Public License 2.0 */
    ZPL_2_0("ZPL-2.0"),
    /** Zope Public License 2.1 */
    ZPL_2_1("ZPL-2.1"),
    /** BSD Zero Clause License */
    _0BSD("0BSD");

    companion object {
        /**
         * Return the enum value for the given [id], or null if it is no SPDX license id.
         */
        fun forId(id: String) = SpdxLicense.values().find { it.id.equals(id, true) }
    }

    /**
     * The full license text as a string.
     */
    val text by lazy {
        val baseId = if (deprecated) {
            id.removeSuffix("+")
        } else {
            id.removeSuffix("-or-later")
        }

        buildString {
            if (baseId != id) {
                append(SpdxLicense::class.java.getResource("/licenses/$baseId-or-later").readText())

                val isGpl = listOf("AGPL-", "GPL-", "LGPL-").any { baseId.startsWith(it) }
                if (isGpl) {
                    // Note: Do not use appendln() here as that would write out platform-native line endings, but we
                    // want to normalize on Unix-style line endings for consistency.
                    append("\n")

                    // For GPL the "or later version" text is just an amendment that reads better as a prefix as then no
                    // text follows the license's final "That's all there is to it!" sentence.
                    append(SpdxLicense::class.java.getResource("/licenses/$baseId").readText())
                }
            } else {
                append(SpdxLicense::class.java.getResource("/licenses/$id").readText())
            }
        }
    }
}
