/*
 * Copyright (C) 2017-2018 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package com.here.ort.spdx

/**
 * An enum containing all SPDX license exception IDs. This class is generated by the Gradle task
 * 'generateSpdxLicenseExceptionList'.
 */
enum class SpdxLicenseException(val id: String) {
    AUTOCONF_EXCEPTION_2_0("Autoconf-exception-2.0"),
    AUTOCONF_EXCEPTION_3_0("Autoconf-exception-3.0"),
    BISON_EXCEPTION_2_2("Bison-exception-2.2"),
    BOOTLOADER_EXCEPTION("Bootloader-exception"),
    CLASSPATH_EXCEPTION_2_0("Classpath-exception-2.0"),
    CLISP_EXCEPTION_2_0("CLISP-exception-2.0"),
    DIGIRULE_FOSS_EXCEPTION("DigiRule-FOSS-exception"),
    ECOS_EXCEPTION_2_0("eCos-exception-2.0"),
    FAWKES_RUNTIME_EXCEPTION("Fawkes-Runtime-exception"),
    FLTK_EXCEPTION("FLTK-exception"),
    FONT_EXCEPTION_2_0("Font-exception-2.0"),
    FREERTOS_EXCEPTION_2_0("freertos-exception-2.0"),
    GCC_EXCEPTION_2_0("GCC-exception-2.0"),
    GCC_EXCEPTION_3_1("GCC-exception-3.1"),
    GNU_JAVAMAIL_EXCEPTION("gnu-javamail-exception"),
    I2P_GPL_JAVA_EXCEPTION("i2p-gpl-java-exception"),
    LIBTOOL_EXCEPTION("Libtool-exception"),
    LINUX_SYSCALL_NOTE("Linux-syscall-note"),
    LLVM_EXCEPTION("LLVM-exception"),
    LZMA_EXCEPTION("LZMA-exception"),
    MIF_EXCEPTION("mif-exception"),
    NOKIA_QT_EXCEPTION_1_1("Nokia-Qt-exception-1.1"),
    OCAML_LGPL_LINKING_EXCEPTION("OCaml-LGPL-linking-exception"),
    OCCT_EXCEPTION_1_0("OCCT-exception-1.0"),
    OPENJDK_ASSEMBLY_EXCEPTION_1_0("OpenJDK-assembly-exception-1.0"),
    OPENVPN_OPENSSL_EXCEPTION("openvpn-openssl-exception"),
    PS_OR_PDF_FONT_EXCEPTION_20170817("PS-or-PDF-font-exception-20170817"),
    QT_GPL_EXCEPTION_1_0("Qt-GPL-exception-1.0"),
    QT_LGPL_EXCEPTION_1_1("Qt-LGPL-exception-1.1"),
    QWT_EXCEPTION_1_0("Qwt-exception-1.0"),
    U_BOOT_EXCEPTION_2_0("u-boot-exception-2.0"),
    WXWINDOWS_EXCEPTION_3_1("WxWindows-exception-3.1"),
    _389_EXCEPTION("389-exception");

    companion object {
        /**
         * Return the enum value for the given [id], or null if it is no SPDX license exception id.
         */
        fun forId(id: String) = SpdxLicenseException.values().find { it.id == id }
    }
}
