/*
 * Copyright (C) 2025 The ORT Project Copyright Holders <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package org.ossreviewtoolkit.plugins.packagemanagers.spdx

import java.io.File

import kotlin.jvm.optionals.getOrNull

import org.apache.logging.log4j.kotlin.logger

import org.ossreviewtoolkit.analyzer.PackageManager
import org.ossreviewtoolkit.analyzer.PackageManagerFactory
import org.ossreviewtoolkit.downloader.VersionControlSystem
import org.ossreviewtoolkit.model.Hash
import org.ossreviewtoolkit.model.HashAlgorithm
import org.ossreviewtoolkit.model.Identifier
import org.ossreviewtoolkit.model.Package
import org.ossreviewtoolkit.model.PackageReference
import org.ossreviewtoolkit.model.Project
import org.ossreviewtoolkit.model.ProjectAnalyzerResult
import org.ossreviewtoolkit.model.RemoteArtifact
import org.ossreviewtoolkit.model.Scope
import org.ossreviewtoolkit.model.VcsInfo
import org.ossreviewtoolkit.model.config.AnalyzerConfiguration
import org.ossreviewtoolkit.model.config.Excludes
import org.ossreviewtoolkit.model.config.Includes
import org.ossreviewtoolkit.model.orNone
import org.ossreviewtoolkit.model.utils.toIdentifier
import org.ossreviewtoolkit.model.utils.toPackageUrl
import org.ossreviewtoolkit.model.utils.toPurl
import org.ossreviewtoolkit.plugins.api.OrtPlugin
import org.ossreviewtoolkit.plugins.api.PluginDescriptor
import org.ossreviewtoolkit.utils.common.enumSetOf
import org.ossreviewtoolkit.utils.ort.DeclaredLicenseProcessor
import org.ossreviewtoolkit.utils.spdx.toExpression
import org.ossreviewtoolkit.utils.spdx.toSpdx
import org.ossreviewtoolkit.utils.spdx.toSpdxOrNull

import org.spdx.library.SpdxModelFactory
import org.spdx.library.model.v3_0_1.core.Element
import org.spdx.library.model.v3_0_1.core.ExternalIdentifierType
import org.spdx.library.model.v3_0_1.core.Hash as SpdxHash
import org.spdx.library.model.v3_0_1.core.Relationship
import org.spdx.library.model.v3_0_1.core.RelationshipType
import org.spdx.library.model.v3_0_1.core.SpdxDocument
import org.spdx.library.model.v3_0_1.simplelicensing.LicenseExpression
import org.spdx.library.model.v3_0_1.software.SpdxPackage as SpdxPackage
import org.spdx.storage.simple.InMemSpdxStore
import org.spdx.v3jsonldstore.JsonLDStore

private const val PROJECT_TYPE = "SPDX"
private const val PACKAGE_TYPE_SPDX = "SPDX"

@OrtPlugin(
    displayName = "SPDX",
    description = "A package manager that uses SPDX version 3 documents as definition files.",
    factory = PackageManagerFactory::class
)
class Spdx(override val descriptor: PluginDescriptor = SpdxFactory.descriptor) : PackageManager(PROJECT_TYPE) {
    init {
        SpdxModelFactory.init()
    }

    override val globsForDefinitionFiles = listOf("*.spdx.json", "*.spdx.jsonld")

    override fun resolveDependencies(
        analysisRoot: File,
        definitionFile: File,
        excludes: Excludes,
        includes: Includes,
        analyzerConfig: AnalyzerConfiguration,
        labels: Map<String, String>
    ): List<ProjectAnalyzerResult> {
        val spdxDocument = parseSpdx3File(definitionFile)

        logger.debug {
            val counts = spdxDocument.elements.groupingBy { it.type }.eachCount().toSortedMap()

            counts.entries.joinToString("\n", prefix = "Found ${spdxDocument.elements.size} SPDX element(s):\n") {
                "\t${it.key}: ${it.value}"
            }
        }

        val spdxPackages = spdxDocument.elements.filterIsInstance<SpdxPackage>()
        val relationships = spdxDocument.elements.filterIsInstance<Relationship>()

        val packagesByScope = spdxPackages.groupBy { pkg ->
            pkg.primaryPurpose.getOrNull()?.name?.lowercase() ?: "other"
        }

        val licenseMap = buildLicenseMap(relationships, spdxDocument.elements)
        val ortPackages = mutableMapOf<Identifier, Package>()
        val scopes = mutableSetOf<Scope>()

        packagesByScope.forEach { (scopeName, packages) ->
            val packageRefs = packages.mapNotNullTo(mutableSetOf()) { spdxPkg ->
                val ortPackage = spdxPkg.toOrtPackage(licenseMap) ?: return@mapNotNullTo null

                ortPackages.merge(ortPackage.id, ortPackage) { existing, other ->
                    // SPDX version 3 files generated by Yocto Linux often contain packages that only differ in the SPDX
                    // ID, but not in other inline properties. As licenses are indirectly defined via relationships
                    // based on the SPDX ID, ensure to merge these.
                    existing.mergeLicenses(other)
                }

                PackageReference(ortPackage.id)
            }

            if (packageRefs.isNotEmpty()) {
                scopes += Scope(name = scopeName, dependencies = packageRefs)
            }
        }

        val projectName = spdxDocument.name.getOrNull() ?: spdxPackages.singleOrNull()?.name?.getOrNull()
            ?: getFallbackProjectName(analysisRoot, definitionFile)

        val project = Project(
            id = Identifier(
                type = projectType,
                namespace = "",
                name = projectName,
                version = ""
            ),
            definitionFilePath = VersionControlSystem.getPathInfo(definitionFile).path,
            authors = emptySet(),
            declaredLicenses = emptySet(),
            // Do not derive the (processed) VCS information from the working directory as done for several other
            // package managers, including SpdxDocumentFile, because the location of the SPDX file usually does not
            // match the location of the project it describes.
            vcs = VcsInfo.EMPTY,
            homepageUrl = "",
            scopeDependencies = scopes
        )

        logger.debug {
            "Resolved ${ortPackages.size} packages in ${scopes.size} scopes: " +
                scopes.joinToString(postfix = ".") { "${it.name} (${it.dependencies.size})" }
        }

        return listOf(ProjectAnalyzerResult(project, ortPackages.values.toSet()))
    }

    /**
     * Build a map keyed by object URI associated with a nested map of the license relationship type associated with the
     * respective licenses.
     */
    private fun buildLicenseMap(
        relationships: Collection<Relationship>,
        elements: Collection<Element>
    ): Map<String, Map<RelationshipType, Set<String>>> {
        val licenseMap = mutableMapOf<String, MutableMap<RelationshipType, MutableSet<String>>>()

        val licenseElements = elements.filterIsInstance<LicenseExpression>()

        relationships.forEach { rel ->
            val fromElement = rel.from ?: return@forEach
            val fromId = fromElement.objectUri

            val toElements = rel.tos.ifEmpty { return@forEach }
            val toIds = toElements.map { it.objectUri }

            licenseElements.filter { it.objectUri in toIds }.mapNotNull { it.licenseExpression }.forEach { licenses ->
                licenseMap.getOrPut(fromId) { mutableMapOf() }
                    .getOrPut(checkNotNull(rel.relationshipType)) { mutableSetOf() } += licenses
            }
        }

        return licenseMap
    }

    private fun SpdxPackage.toOrtPackage(licenseMap: Map<String, Map<RelationshipType, Set<String>>>): Package? {
        val pkgName = name.getOrNull() ?: return null
        val pkgVersion = packageVersion.getOrNull().orEmpty()

        val purl = externalIdentifiers.filter {
            it.externalIdentifierType == ExternalIdentifierType.PACKAGE_URL
        }.firstNotNullOfOrNull { it.identifier }

        val cpe = externalIdentifiers.filter {
            it.externalIdentifierType in enumSetOf(ExternalIdentifierType.CPE22, ExternalIdentifierType.CPE23)
        }.firstNotNullOfOrNull { it.identifier }

        // Prefer a PURL as it might contain proper type and namespace information.
        val id = purl?.toPackageUrl()?.toIdentifier() ?: Identifier(
            type = PACKAGE_TYPE_SPDX,
            namespace = "",
            name = pkgName,
            version = pkgVersion
        )

        val url = downloadLocation.getOrNull()
        val sourceArtifact = if (!url.isNullOrBlank()) {
            val hash = verifiedUsings.filterIsInstance<SpdxHash>().firstOrNull()?.let { spdxHash ->
                val algorithm = spdxHash.algorithm
                val value = spdxHash.hashValue
                if (algorithm != null && value != null) {
                    Hash(value, HashAlgorithm.fromString(algorithm.longName))
                } else {
                    Hash.NONE
                }
            }.orNone()

            RemoteArtifact(url, hash)
        } else {
            RemoteArtifact.EMPTY
        }

        val pkgLicenses = licenseMap[objectUri]
        val declaredLicenses = pkgLicenses?.get(RelationshipType.HAS_DECLARED_LICENSE).orEmpty()
        val concludedLicenses = pkgLicenses?.get(RelationshipType.HAS_CONCLUDED_LICENSE).orEmpty()

        val description = description.getOrNull() ?: summary.getOrNull()

        return Package(
            id = id,
            purl = purl ?: id.toPurl(),
            cpe = cpe,
            authors = emptySet(),
            declaredLicenses = declaredLicenses,
            concludedLicense = if (concludedLicenses.size > 1) {
                logger.warn { "Multiple concluded licenses found for package '$name', using only the first one." }
                concludedLicenses.first().toSpdx()
            } else {
                concludedLicenses.singleOrNull()?.toSpdxOrNull()
            },
            description = description.orEmpty(),
            homepageUrl = homePage.getOrNull().orEmpty(),
            binaryArtifact = RemoteArtifact.EMPTY,
            sourceArtifact = sourceArtifact,
            vcs = VcsInfo.EMPTY
        )
    }
}

private fun Package.mergeLicenses(other: Package): Package {
    val mergedDeclaredLicenses = declaredLicenses + other.declaredLicenses
    val mergedConcludedLicense = setOfNotNull(concludedLicense, other.concludedLicense).toExpression()

    return copy(
        declaredLicenses = mergedDeclaredLicenses,
        declaredLicensesProcessed = DeclaredLicenseProcessor.process(mergedDeclaredLicenses),
        concludedLicense = mergedConcludedLicense
    )
}

private fun parseSpdx3File(spdxFile: File): SpdxDocument {
    val baseStore = InMemSpdxStore()
    val store = JsonLDStore(baseStore)
    return spdxFile.inputStream().use { store.deSerialize(it, /* overwrite = */ false) }
}
