[tool.poetry]
name = "example"
version = "1.0.0"
description = "example project"
authors = ["author name <author@example.com>"]
packages = [
    {include = "example"}
]
include = [
    {path = "example/py.typed"},
]

[tool.poetry.dependencies]
python = "^3.6"
graphviz = ">=0.13.2,<0.20.0"
jinja2 = ">=2.10,<4.0"
contextvars = { version = "^2.4", python = "~3.6" }

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pylint = "^2.7"
black = {version = "^19.0", allow-prereleases = true}
rope = "^0.14.0"
isort = "^4.3"

[tool.black]
line-length = 120
