name: subproject
description: A sample subproject.
version: 1.0.0
authors:
  - "The ORT Project Authors"
homepage: https://ossreviewtoolkit.org/
repository: https://github.com/oss-review-toolkit/ort.git

dependencies:
  typed_data: 1.3.1

environment:
  sdk: ">=2.10.0 <3.0.0"
