/*
 * Copyright (C) 2019 The ORT Project Copyright Holders <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

import type { JSX } from "react";

import { OrtLogo } from "@/components/OrtLogo";
import { Url } from "@/components/Shared";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";

// The About page: what this report is, plus ORT project links and license/attribution details.
function About(): JSX.Element {
    return (
        <div className="mx-auto flex max-w-4xl flex-col gap-4">
            <Card>
                <CardHeader>
                    <CardTitle>About this report</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4 text-sm leading-relaxed">
                    <OrtLogo className="h-10 w-auto" />
                    <p>
                        This report was generated by the{" "}
                        <Url href="https://oss-review-toolkit.org/">OSS Review Toolkit (ORT)</Url> - a FOSS policy
                        automation and orchestration toolkit that you can use to manage your (open source) software
                        dependencies in a strategic, safe and efficient manner, and to satisfy common obligations.
                    </p>
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                    <CardTitle>Licenses</CardTitle>
                </CardHeader>
                <CardContent className="text-sm leading-relaxed">
                    <p>
                        ORT is licensed under the Apache License, Version 2.0 (SPDX-License-Identifier: Apache-2.0) and
                        bundles third-party components distributed under other open source licenses. See the{" "}
                        <Url href="https://github.com/oss-review-toolkit/ort">OSS Review Toolkit code repository</Url>{" "}
                        for documentation and further details.
                    </p>
                </CardContent>
            </Card>
        </div>
    );
}

export { About };
export default About;
