name: Docusaurus Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Docusaurus Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: docusaurus/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: docusaurus
      - name: Test build
        run: npm run build
        working-directory: docusaurus
