name: Native Build

on:
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.logging.stacktrace=all

permissions: read-all

jobs:
  analyzer-only:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@27b360dbb857524eaf0b4c4cef364d38e5b4f173 # v1.6.7
        with:
          distribution: graalvm
          java-version: 25
          native-image-job-reports: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f5f9adaf7d9fecd50b5935e54106014257a94e6 # v6.4.0
      - name: Build Executable
        run: ./gradlew -P cliAnalyzerOnly=true --no-configuration-cache :cli:nativeCompile
      - name: Compress Executable
        uses: crazy-max/ghaction-upx@c83f378efc804f828e988debb88ed6116feb2368 # v4.0.0
        with:
          files: cli/build/native/nativeCompile/ort
      - name: Upload Executable
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: ORT Analyzer-only
          path: cli/build/native/nativeCompile/ort
          archive: false
          retention-days: 7
