name: Native Build

on:
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

permissions: read-all

jobs:
  analyzer-only:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@60c26726de13f8b90771df4bc1641a52a3159994 # v1.5.2
        with:
          distribution: graalvm
          java-version: 25
          native-image-job-reports: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - name: Build Executable
        run: ./gradlew -P cliAnalyzerOnly=true --no-configuration-cache :cli:nativeCompile
      - name: Compress Executable
        uses: crazy-max/ghaction-upx@c83f378efc804f828e988debb88ed6116feb2368 # v4.0.0
        with:
          files: cli/build/native/nativeCompile/ort
      - name: Upload Executable
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ORT Analyzer-only
          path: cli/build/native/nativeCompile/ort
          archive: false
          retention-days: 7
