name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to release from"
        required: true
        type: string

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  publish:
    env:
      ORT_VERSION: ${{ inputs.tag || github.ref_name }}
    permissions:
      attestations: write
      contents: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          ref: ${{ env.ORT_VERSION }}
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
        with:
          dependency-graph: generate-and-submit
      - name: Publish to OSSRH
        env:
          GITHUB_DEPENDENCY_GRAPH_REF: refs/heads/main
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_RELEASE_SIGNING_ENABLED: true
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew --no-configuration-cache publishAndReleaseToMavenCentral
      - name: Build ORT Distributions
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew :cli:signDistTar :cli:signDistZip :helper-cli:signDistTar :helper-cli:signDistZip
      - name: Generate Release Notes
        run: ./gradlew -q printChangeLog > RELEASE_NOTES.md
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $ORT_VERSION --notes-file RELEASE_NOTES.md \
              ./cli/build/distributions/ort-$ORT_VERSION.{tgz,zip}* \
              ./helper-cli/build/distributions/orth-$ORT_VERSION.{tgz,zip}*
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1
        with:
          subject-path: |
            ./cli/build/distributions/ort-${{ env.ORT_VERSION }}.tgz
            ./cli/build/distributions/ort-${{ env.ORT_VERSION }}.zip
            ./helper-cli/build/distributions/orth-${{ env.ORT_VERSION }}.tgz
            ./helper-cli/build/distributions/orth-${{ env.ORT_VERSION }}.zip
